// ===============================================================
// JukenWords.gs
// 大学受験モード（英単語）のデータ
//
//   no   : 単語帳の見出し語番号（出題順・範囲指定のキー）
//   en   : 英単語（第1問の答え。英字でタイプさせる）
//   ja   : 日本語の意味（第1問の問題文として表示）
//   kana : 第2問の答え（ひらがな。ローマ字入力でタイプさせる）
//   ex   : 例文（第2問で対象語を空欄にして表示＋音声読み上げ）
//   exja : 例文の和訳（正解後に表示）
//
// 見出し語と番号は利用者が所有する単語帳の並びに対応させているが、
// 訳文・例文・和訳はすべて本アプリ用の書き下ろし。発音は端末側の
// 音声合成（Web Speech API）で生成するため音声ファイルは持たない。
// ===============================================================

const JUKEN_WORDS = [
  { no:    1, en: "diet", ja: "食事／食生活", kana: "しょくじ", ex: "A balanced diet keeps your body strong.", exja: "バランスの取れた食事は体を丈夫に保つ。" },
  { no:    1, en: "dietary", ja: "食事の／飲食物の", kana: "しょくじの", ex: "The doctor gave my father dietary advice.", exja: "医者は父に食事についての助言をした。" },
  { no:    2, en: "ingredient", ja: "材料／成分", kana: "ざいりょう", ex: "Please mix all the ingredients in a large bowl.", exja: "大きなボウルで材料をすべて混ぜてください。" },
  { no:    3, en: "preparation", ja: "準備／下ごしらえ", kana: "じゅんび", ex: "Preparation for the school festival took two weeks.", exja: "学園祭の準備には二週間かかった。" },
  { no:    3, en: "prepare", ja: "〜を用意する／準備する", kana: "よういする", ex: "She prepared a simple lunch for her brother.", exja: "彼女は弟のために簡単な昼食を用意した。" },
  { no:    4, en: "boil", ja: "〜を沸かす／ゆでる", kana: "わかす", ex: "Boil the water before you add the noodles.", exja: "麺を入れる前にお湯を沸かしなさい。" },
  { no:    5, en: "bake", ja: "〜を（オーブンで）焼く", kana: "やく", ex: "My sister baked a chocolate cake yesterday.", exja: "姉は昨日チョコレートケーキを焼いた。" },
  { no:    5, en: "broil", ja: "〜を直火で焼く", kana: "じかびでやく", ex: "The cook broiled the fish over a hot fire.", exja: "料理人は強い火で魚を直火で焼いた。" },
  { no:    5, en: "roast", ja: "〜をあぶり焼きにする", kana: "あぶりやき", ex: "They roasted a whole chicken for the party.", exja: "彼らはパーティーのために鶏を丸ごとあぶり焼きにした。" },
  { no:    6, en: "fry", ja: "〜を油でいためる／揚げる", kana: "いためる", ex: "He fried some onions in a small pan.", exja: "彼は小さな鍋で玉ねぎをいためた。" },
  { no:    7, en: "taste", ja: "味／〜の味がする", kana: "あじ", ex: "This soup has a slightly sweet taste.", exja: "このスープは少し甘い味がする。" },
  { no:    7, en: "tasty", ja: "おいしい", kana: "おいしい", ex: "The bread from that little shop is very tasty.", exja: "あの小さな店のパンはとてもおいしい。" },
  { no:    8, en: "smell", ja: "におい／〜のにおいがする", kana: "におい", ex: "The kitchen smelled of fresh coffee.", exja: "台所はいれたてのコーヒーのにおいがした。" },
  { no:    9, en: "bite", ja: "〜にかみつく／かむ", kana: "かみつく", ex: "The little dog bit my finger.", exja: "その小さな犬は私の指にかみついた。" },
  { no:    9, en: "chew", ja: "〜をよくかむ", kana: "よくかむ", ex: "You should chew your food slowly.", exja: "食べ物はゆっくりよくかむべきだ。" },
  { no:   10, en: "swallow", ja: "〜を飲み込む", kana: "のみこむ", ex: "He swallowed the medicine with a glass of water.", exja: "彼はコップ一杯の水で薬を飲み込んだ。" },

  { no:   11, en: "serve", ja: "（食事）を出す／〜に仕える", kana: "ていきょうする", ex: "That restaurant serves breakfast until eleven.", exja: "あのレストランは十一時まで朝食を出す。" },
  { no:   11, en: "service", ja: "接客／奉仕／公共事業", kana: "せっきゃく", ex: "The service at the old hotel was excellent.", exja: "その古いホテルの接客はすばらしかった。" },
  { no:   12, en: "feed", ja: "〜に食べ物を与える", kana: "えさをやる", ex: "She feeds her cat twice a day.", exja: "彼女は猫に一日二回えさをやる。" },
  { no:   12, en: "food", ja: "食べ物", kana: "たべもの", ex: "We bought food for the camping trip.", exja: "私たちはキャンプ旅行のための食べ物を買った。" },
  { no:   13, en: "cash", ja: "現金", kana: "げんきん", ex: "I paid for the concert tickets in cash.", exja: "私はコンサートの券の代金を現金で払った。" },
  { no:   14, en: "discount", ja: "割引", kana: "わりびき", ex: "The store offered a big discount on winter coats.", exja: "その店は冬のコートに大きな割引をつけた。" },
  { no:   15, en: "bargain", ja: "買い得品／取引する", kana: "かいどく", ex: "This jacket was a real bargain.", exja: "この上着は本当にお買い得だった。" },
  { no:   16, en: "reason", ja: "理由／理性", kana: "りゆう", ex: "Tell me the reason you were late this morning.", exja: "今朝遅れた理由を教えてください。" },
  { no:   16, en: "reasonable", ja: "（値段が）手ごろな／妥当な", kana: "てごろな", ex: "The price of this bike is quite reasonable.", exja: "この自転車の値段はかなり手ごろだ。" },
  { no:   17, en: "spend", ja: "（お金・時間）を使う", kana: "つかう", ex: "I spent three hours on my science homework.", exja: "私は理科の宿題に三時間使った。" },
  { no:   18, en: "sweep", ja: "〜を（ほうきで）掃く", kana: "ほうきではく", ex: "He swept the floor after dinner.", exja: "彼は夕食のあとに床を掃いた。" },
  { no:   18, en: "vacuum", ja: "掃除機／〜に掃除機をかける", kana: "そうじき", ex: "She vacuumed the living room this morning.", exja: "彼女は今朝、居間に掃除機をかけた。" },
  { no:   19, en: "wipe", ja: "〜をふき取る／ぬぐう", kana: "ふきとる", ex: "Wipe the table with this wet cloth.", exja: "このぬれた布でテーブルをふき取りなさい。" },
  { no:   20, en: "cloth", ja: "布／きれ", kana: "ぬの", ex: "She covered the box with a blue cloth.", exja: "彼女は箱を青い布でおおった。" },
  { no:   20, en: "clothes", ja: "衣服", kana: "いふく", ex: "Put your dirty clothes in the basket.", exja: "汚れた衣服はかごに入れなさい。" },
  { no:   20, en: "clothing", ja: "衣類（全体）", kana: "いるい", ex: "That shop sells clothing for small children.", exja: "あの店は小さな子ども用の衣類を売っている。" },

  { no:   21, en: "hang", ja: "〜をつるす／かける", kana: "つるす", ex: "Hang your coat on the hook by the door.", exja: "上着をドアのそばのフックにかけなさい。" },
  { no:   22, en: "housework", ja: "家事／家の仕事", kana: "いえのしごと", ex: "My brother helps with the housework on weekends.", exja: "兄は週末に家事を手伝う。" },
  { no:   23, en: "laundry", ja: "洗濯／洗濯物", kana: "せんたく", ex: "I do the laundry every Sunday morning.", exja: "私は毎週日曜の朝に洗濯をする。" },
  { no:   24, en: "celebrate", ja: "〜を祝う", kana: "いわう", ex: "We celebrated my mother's birthday at home.", exja: "私たちは家で母の誕生日を祝った。" },
  { no:   24, en: "celebration", ja: "祝賀／お祝いの行事", kana: "しゅくが", ex: "The village held a celebration after the harvest.", exja: "村は収穫のあとに祝賀の行事を開いた。" },
  { no:   24, en: "celebrity", ja: "有名人", kana: "ゆうめいじん", ex: "A celebrity from Tokyo visited our small town.", exja: "東京の有名人が私たちの小さな町を訪れた。" },
  { no:   25, en: "ceremony", ja: "式／儀式", kana: "しきてん", ex: "The opening ceremony began at ten o'clock.", exja: "開会の式典は十時に始まった。" },
  { no:   26, en: "marriage", ja: "結婚", kana: "けっこん", ex: "Their marriage has lasted for twenty years.", exja: "彼らの結婚は二十年続いている。" },
  { no:   26, en: "marry", ja: "〜と結婚する", kana: "けっこんする", ex: "She married a teacher from her hometown.", exja: "彼女は故郷の先生と結婚した。" },
  { no:   27, en: "anniversary", ja: "記念日", kana: "きねんび", ex: "Our school's anniversary falls in May.", exja: "私たちの学校の記念日は五月にある。" },
  { no:   28, en: "funeral", ja: "葬式", kana: "そうしき", ex: "Many people came to his grandfather's funeral.", exja: "多くの人が彼の祖父の葬式に来た。" },
  { no:   29, en: "floor", ja: "床／（建物の）階", kana: "ゆか", ex: "The wooden floor felt cold under my feet.", exja: "木の床は足の下で冷たく感じた。" },
  { no:   29, en: "story", ja: "物語／（建物の）階", kana: "ものがたり", ex: "That old brown building has five stories.", exja: "あの古い茶色の建物は五階建てだ。" },
  { no:   30, en: "brick", ja: "れんが", kana: "れんが", ex: "The garden wall was built with red bricks.", exja: "庭の壁は赤いれんがで作られていた。" },

  { no:   31, en: "ceiling", ja: "天井", kana: "てんじょう", ex: "A large lamp hangs from the ceiling.", exja: "大きなランプが天井からつるされている。" },
  { no:   32, en: "backyard", ja: "裏庭", kana: "うらにわ", ex: "The children played catch in the backyard.", exja: "子どもたちは裏庭でキャッチボールをした。" },
  { no:   32, en: "garden", ja: "庭／庭園", kana: "ていえん", ex: "My grandmother grows roses in her garden.", exja: "祖母は庭でバラを育てている。" },
  { no:   32, en: "yard", ja: "庭／敷地", kana: "しきち", ex: "They parked the old truck in the yard.", exja: "彼らは古いトラックを敷地に止めた。" },
  { no:   33, en: "staircase", ja: "階段（全体）", kana: "かいだんぜんたい", ex: "The old staircase creaked under our feet.", exja: "古い階段は私たちの足の下できしんだ。" },
  { no:   33, en: "stairs", ja: "階段", kana: "かいだん", ex: "She ran up the stairs to her room.", exja: "彼女は自分の部屋へ階段を駆け上がった。" },
  { no:   34, en: "downstairs", ja: "階下へ／下の階に", kana: "したのかい", ex: "He went downstairs to answer the phone.", exja: "彼は電話に出るために階下へ行った。" },
  { no:   34, en: "upstairs", ja: "階上へ／上の階に", kana: "うえのかい", ex: "My room is upstairs, next to the bathroom.", exja: "私の部屋は上の階の、浴室の隣だ。" },
  { no:   35, en: "follow", ja: "〜について行く／〜に従う", kana: "ついていく", ex: "A puppy followed me all the way to school.", exja: "子犬が学校までずっと私について来た。" },
  { no:   35, en: "obey", ja: "〜に従う／〜を守る", kana: "したがう", ex: "Every driver must obey the traffic rules.", exja: "すべての運転手は交通規則に従わなければならない。" },
  { no:   36, en: "rule", ja: "規則／〜を支配する", kana: "きそく", ex: "Our club has one simple rule about practice.", exja: "私たちの部には練習について簡単な規則が一つある。" },
  { no:   37, en: "notice", ja: "〜に気づく／掲示", kana: "きづく", ex: "I noticed a small mistake in the report.", exja: "私は報告書の小さな誤りに気づいた。" },
  { no:   37, en: "noticeable", ja: "目立つ／はっきり分かる", kana: "めだつ", ex: "There was a noticeable change in his voice.", exja: "彼の声には目立つ変化があった。" },
  { no:   38, en: "noise", ja: "騒音／物音", kana: "そうおん", ex: "The noise from the street woke me up.", exja: "通りからの騒音で私は目が覚めた。" },
  { no:   38, en: "sound", ja: "音／〜に聞こえる", kana: "おと", ex: "I heard the sound of rain on the roof.", exja: "屋根に当たる雨の音が聞こえた。" },
  { no:   39, en: "split", ja: "〜を分ける／割る", kana: "わける", ex: "They split the pizza into six pieces.", exja: "彼らはピザを六切れに分けた。" },
  { no:   40, en: "bill", ja: "請求書／紙幣", kana: "せいきゅうしょ", ex: "The waiter brought us the bill after dessert.", exja: "給仕はデザートのあとに請求書を持ってきた。" },
  { no:   40, en: "note", ja: "覚え書き／紙幣", kana: "おぼえがき", ex: "She left a short note on the kitchen table.", exja: "彼女は台所のテーブルに短い覚え書きを残した。" },

  { no:   41, en: "precious", ja: "貴重な／大切な", kana: "きちょうな", ex: "Water is precious in that dry country.", exja: "その乾いた国では水は貴重だ。" },
  { no:   42, en: "memorable", ja: "忘れられない／記憶に残る", kana: "わすれがたい", ex: "The trip to the small island was memorable.", exja: "その小さな島への旅は忘れがたいものだった。" },
  { no:   42, en: "memorial", ja: "記念碑／記念の", kana: "きねんひ", ex: "They built a memorial for the lost sailors.", exja: "彼らは亡くなった船乗りのために記念碑を建てた。" },
  { no:   42, en: "memory", ja: "記憶／思い出", kana: "きおく", ex: "I still have a clear memory of that summer.", exja: "私は今もあの夏の記憶をはっきり持っている。" },
  { no:   43, en: "case", ja: "場合／事例", kana: "ばあい", ex: "In that case, we should leave early.", exja: "その場合、私たちは早く出発すべきだ。" },
  { no:   44, en: "event", ja: "出来事／行事", kana: "できごと", ex: "Winning the contest was a big event in her life.", exja: "その大会に勝ったことは彼女の人生の大きな出来事だった。" },
  { no:   45, en: "accident", ja: "事故", kana: "じこ", ex: "A traffic accident closed the main road.", exja: "交通事故で幹線道路が通れなくなった。" },
  { no:   45, en: "accidental", ja: "偶然の／思いがけない", kana: "ぐうぜんの", ex: "Their meeting at the station was completely accidental.", exja: "駅での彼らの出会いは全くの偶然だった。" },
  { no:   46, en: "nephew", ja: "おい", kana: "おい", ex: "My nephew is only four years old.", exja: "私のおいはまだ四歳だ。" },
  { no:   46, en: "niece", ja: "めい", kana: "めい", ex: "Her niece won first prize in the drawing contest.", exja: "彼女のめいは絵のコンテストで一等賞を取った。" },
  { no:   47, en: "cousin", ja: "いとこ", kana: "いとこ", ex: "My cousin lives in a small fishing town.", exja: "私のいとこは小さな漁師町に住んでいる。" },
  { no:   48, en: "relative", ja: "親戚／相対的な", kana: "しんせき", ex: "Many relatives came to our house at New Year.", exja: "正月には多くの親戚が家に来た。" },
  { no:   49, en: "neighbor", ja: "隣人／近所の人", kana: "りんじん", ex: "Our neighbor lent us a ladder yesterday.", exja: "昨日、隣人がはしごを貸してくれた。" },
  { no:   49, en: "neighborhood", ja: "近所／地域", kana: "きんじょ", ex: "There is a nice park in our neighborhood.", exja: "私たちの近所には良い公園がある。" },
  { no:   50, en: "citizen", ja: "市民／国民", kana: "しみん", ex: "Every citizen has the right to vote.", exja: "すべての市民は投票する権利を持つ。" },
  { no:   50, en: "citizenship", ja: "市民権／国籍", kana: "こくせき", ex: "He got Japanese citizenship last year.", exja: "彼は昨年、日本の国籍を得た。" },

  { no:   51, en: "strange", ja: "奇妙な／見知らぬ", kana: "きみょうな", ex: "I heard a strange noise under the floor.", exja: "床の下で奇妙な物音が聞こえた。" },
  { no:   51, en: "stranger", ja: "見知らぬ人", kana: "みしらぬひと", ex: "A stranger asked me for directions to the museum.", exja: "見知らぬ人が私に博物館への道をたずねた。" },
  { no:   52, en: "accept", ja: "〜を受け入れる", kana: "うけいれる", ex: "She accepted his apology with a smile.", exja: "彼女は笑顔で彼の謝罪を受け入れた。" },
  { no:   52, en: "acceptable", ja: "許容できる／申し分のない", kana: "きょようできる", ex: "His answer was acceptable to the teacher.", exja: "彼の答えは先生にとって許容できるものだった。" },
  { no:   52, en: "acceptance", ja: "承諾／受け入れ", kana: "しょうだく", ex: "Her acceptance of the offer surprised us all.", exja: "彼女がその申し出を承諾したことは私たち全員を驚かせた。" },
  { no:   53, en: "refuse", ja: "〜を断る／拒む", kana: "ことわる", ex: "He refused the invitation politely.", exja: "彼はその招待を丁寧に断った。" },
  { no:   53, en: "reject", ja: "〜を退ける／不採用にする", kana: "しりぞける", ex: "The company rejected my first design.", exja: "その会社は私の最初の案を退けた。" },
  { no:   53, en: "rejection", ja: "拒絶／不採用", kana: "きょぜつ", ex: "The rejection of his plan made him angry.", exja: "計画の拒絶は彼を怒らせた。" },
  { no:   54, en: "lift", ja: "〜を持ち上げる", kana: "もちあげる", ex: "Can you lift this heavy box for me?", exja: "この重い箱を持ち上げてくれますか。" },
  { no:   55, en: "drop", ja: "〜を落とす／落ちる", kana: "おとす", ex: "I dropped my pen under the desk.", exja: "私は机の下にペンを落とした。" },
  { no:   56, en: "pass", ja: "〜を通り過ぎる／合格する", kana: "とおりすぎる", ex: "We passed a small church on the way home.", exja: "帰り道で小さな教会を通り過ぎた。" },
  { no:   57, en: "fail", ja: "失敗する／〜しそこなう", kana: "しっぱいする", ex: "They failed in their first attempt.", exja: "彼らは最初の試みで失敗した。" },
  { no:   57, en: "failure", ja: "失敗／うまくいかないこと", kana: "しくじり", ex: "His failure taught him an important lesson.", exja: "彼の失敗は彼に大切な教訓を教えた。" },
  { no:   58, en: "severe", ja: "厳しい／深刻な", kana: "しんこくな", ex: "The town suffered severe damage from the storm.", exja: "その町は嵐で深刻な被害を受けた。" },
  { no:   59, en: "strict", ja: "（規則や人が）厳しい", kana: "きびしい", ex: "Our coach is strict about being on time.", exja: "私たちのコーチは時間を守ることに厳しい。" },
  { no:   59, en: "strictly", ja: "厳しく／厳密に", kana: "げんみつに", ex: "Smoking is strictly forbidden in this building.", exja: "この建物では喫煙は厳しく禁じられている。" },
  { no:   60, en: "correct", ja: "正しい／〜を訂正する", kana: "ただしい", ex: "Only one of the four answers is correct.", exja: "四つの答えのうち正しいのは一つだけだ。" },
  { no:   60, en: "incorrect", ja: "誤った／正しくない", kana: "あやまった", ex: "The date on the poster was incorrect.", exja: "ポスターの日付は誤っていた。" },

  { no:   61, en: "accuracy", ja: "正確さ", kana: "せいかくさ", ex: "The accuracy of his report impressed the class.", exja: "彼の報告の正確さはクラスを感心させた。" },
  { no:   61, en: "accurate", ja: "正確な", kana: "せいかくな", ex: "We need an accurate map of this area.", exja: "この地域の正確な地図が必要だ。" },
  { no:   61, en: "inaccurate", ja: "不正確な", kana: "ふせいかくな", ex: "The old clock in the hall is a little inaccurate.", exja: "広間の古い時計は少し不正確だ。" },
  { no:   62, en: "awe", ja: "畏敬の念／驚嘆", kana: "いけい", ex: "The huge waterfall filled us with awe.", exja: "その巨大な滝は私たちを畏敬の念で満たした。" },
  { no:   62, en: "awful", ja: "ひどい／実にいやな", kana: "ひどい", ex: "The weather was awful during our whole trip.", exja: "旅行の間ずっと天気はひどかった。" },
  { no:   63, en: "terrible", ja: "恐ろしい／ひどい", kana: "おそろしい", ex: "The storm caused terrible damage to the village.", exja: "嵐は村に恐ろしい被害をもたらした。" },
  { no:   63, en: "terror", ja: "恐怖", kana: "きょうふ", ex: "The children screamed in terror.", exja: "子どもたちは恐怖で叫んだ。" },
  { no:   64, en: "horrible", ja: "ぞっとする／実にひどい", kana: "ぞっとする", ex: "He told us a horrible story about the dark cave.", exja: "彼は暗い洞窟についてぞっとする話をした。" },
  { no:   64, en: "horror", ja: "おののき／強い恐怖", kana: "おののき", ex: "She watched the burning house in horror.", exja: "彼女はおののきながら燃える家を見ていた。" },
  { no:   65, en: "live", ja: "住む／生きる", kana: "すむ", ex: "They live near the wide river.", exja: "彼らは広い川の近くに住んでいる。" },
  { no:   65, en: "lively", ja: "活気のある／元気な", kana: "かっきのある", ex: "The morning market was very lively.", exja: "朝の市場はとても活気があった。" },
  { no:   66, en: "alive", ja: "生きている", kana: "いきている", ex: "The old cherry tree is still alive.", exja: "その古い桜の木はまだ生きている。" },
  { no:   67, en: "loud", ja: "大声の／音が大きい", kana: "おおごえの", ex: "His loud voice filled the small room.", exja: "彼の大きな声が小さな部屋を満たした。" },
  { no:   68, en: "aloud", ja: "声に出して", kana: "こえにだして", ex: "Please read this poem aloud.", exja: "この詩を声に出して読んでください。" },
  { no:   68, en: "silently", ja: "黙って／静かに", kana: "だまって", ex: "He silently left the room and closed the door.", exja: "彼は黙って部屋を出て、ドアを閉めた。" },
  { no:   69, en: "impossible", ja: "不可能な", kana: "ふかのうな", ex: "It is impossible to finish this in one day.", exja: "これを一日で終えるのは不可能だ。" },
  { no:   69, en: "possibility", ja: "可能性", kana: "かのうせい", ex: "There is a possibility of snow tonight.", exja: "今夜は雪の可能性がある。" },
  { no:   69, en: "possible", ja: "可能な／ありうる", kana: "かのうな", ex: "Come as early as possible tomorrow.", exja: "明日はできるだけ早く来てください。" },
  { no:   70, en: "necessarily", ja: "必ずしも（〜ない）", kana: "かならずしも", ex: "A long book is not necessarily a good one.", exja: "長い本が必ずしも良い本とは限らない。" },
  { no:   70, en: "necessary", ja: "必要な", kana: "ひつような", ex: "Warm clothes are necessary in the mountains.", exja: "山では暖かい服が必要だ。" },
  { no:   70, en: "necessity", ja: "必要性／必需品", kana: "ひつようせい", ex: "Water is a necessity for every living thing.", exja: "水はすべての生き物にとって必要なものだ。" },
  { no:   70, en: "unnecessary", ja: "不必要な", kana: "ふひつような", ex: "He bought many unnecessary things at the sale.", exja: "彼は安売りで不必要な物をたくさん買った。" },

  { no:   71, en: "danger", ja: "危険", kana: "きけん", ex: "The sign warns drivers of danger ahead.", exja: "その標識は運転手に前方の危険を知らせている。" },
  { no:   71, en: "dangerous", ja: "危険な", kana: "きけんな", ex: "Swimming in that river is dangerous.", exja: "あの川で泳ぐのは危険だ。" },
  { no:   71, en: "safe", ja: "安全な／金庫", kana: "あんぜんな", ex: "This quiet street is safe for children.", exja: "この静かな通りは子どもにとって安全だ。" },
  { no:   72, en: "convenience", ja: "便利さ／好都合", kana: "べんりさ", ex: "The convenience of the new station pleased everyone.", exja: "新しい駅の便利さはみんなを喜ばせた。" },
  { no:   72, en: "convenient", ja: "便利な／都合のよい", kana: "べんりな", ex: "A small umbrella is convenient on rainy days.", exja: "小さな傘は雨の日に便利だ。" },
  { no:   72, en: "inconvenient", ja: "不便な／都合の悪い", kana: "ふべんな", ex: "The bus times are inconvenient for students.", exja: "バスの時刻は学生には不便だ。" },
  { no:   73, en: "unusual", ja: "珍しい／異常な", kana: "めずらしい", ex: "Snow in April is unusual in this town.", exja: "この町で四月に雪が降るのは珍しい。" },
  { no:   73, en: "usual", ja: "いつもの／普通の", kana: "いつもの", ex: "He sat in his usual seat by the window.", exja: "彼は窓際のいつもの席に座った。" },
  { no:   74, en: "fun", ja: "楽しみ／楽しいこと", kana: "たのしみ", ex: "We had a lot of fun at the beach.", exja: "私たちは浜辺で大いに楽しんだ。" },
  { no:   74, en: "funny", ja: "おかしい／こっけいな", kana: "おかしい", ex: "Her funny story made everyone laugh.", exja: "彼女のおかしな話はみんなを笑わせた。" },
  { no:   75, en: "rude", ja: "失礼な／無礼な", kana: "しつれいな", ex: "It is rude to point at people.", exja: "人を指さすのは失礼だ。" },
  { no:   76, en: "wisdom", ja: "知恵", kana: "ちえ", ex: "We learned much from our grandmother's wisdom.", exja: "私たちは祖母の知恵から多くを学んだ。" },
  { no:   76, en: "wise", ja: "賢い／賢明な", kana: "かしこい", ex: "It was wise of you to bring a map.", exja: "地図を持ってきたのは賢かった。" },
  { no:   77, en: "clear", ja: "澄んだ／明らかな", kana: "すんだ", ex: "The sky was clear after the evening rain.", exja: "夕方の雨のあと、空は澄んでいた。" },
  { no:   77, en: "obvious", ja: "明らかな／見え見えの", kana: "あきらかな", ex: "It was obvious that he was very tired.", exja: "彼がとても疲れているのは明らかだった。" },
  { no:   77, en: "obviously", ja: "明らかに", kana: "あきらかに", ex: "She was obviously happy about the news.", exja: "彼女はその知らせを明らかに喜んでいた。" },
  { no:   78, en: "fortunate", ja: "幸運な", kana: "こううんな", ex: "We were fortunate to find two seats.", exja: "私たちは席を二つ見つけられて幸運だった。" },
  { no:   78, en: "fortunately", ja: "幸いにも", kana: "さいわいにも", ex: "Fortunately, no one was hurt in the fire.", exja: "幸いにも火事で誰もけがをしなかった。" },
  { no:   78, en: "lucky", ja: "運のよい", kana: "うんがよい", ex: "You are lucky to have such kind friends.", exja: "そんな親切な友達がいるとは運がよい。" },
  { no:   79, en: "pity", ja: "哀れみ／残念なこと", kana: "あわれみ", ex: "She felt pity for the lost kitten.", exja: "彼女は迷子の子猫に哀れみを感じた。" },
  { no:   80, en: "shame", ja: "恥／残念なこと", kana: "はじ", ex: "He felt shame after telling the lie.", exja: "うそをついたあと、彼は恥を感じた。" },

  { no:   81, en: "impolite", ja: "無作法な／失礼な", kana: "ぶさほうな", ex: "It is impolite to talk with your mouth full.", exja: "口に物を入れたまま話すのは無作法だ。" },
  { no:   81, en: "polite", ja: "礼儀正しい", kana: "れいぎただしい", ex: "The boy gave a polite answer to the guest.", exja: "その少年は客に礼儀正しい返事をした。" },
  { no:   82, en: "smart", ja: "頭のよい／賢い", kana: "あたまがよい", ex: "My smart little sister solved the puzzle quickly.", exja: "頭のよい妹はすぐにパズルを解いた。" },
  { no:   83, en: "selfish", ja: "自分勝手な／利己的な", kana: "じぶんかって", ex: "His selfish behavior upset the whole team.", exja: "彼の自分勝手な行動はチーム全体を困らせた。" },
  { no:   83, en: "selfishness", ja: "利己心／身勝手さ", kana: "りこしん", ex: "Her selfishness cost her many friends.", exja: "彼女の利己心は多くの友人を失わせた。" },
  { no:   84, en: "lazy", ja: "なまけた／怠惰な", kana: "なまけた", ex: "The lazy cat slept all afternoon.", exja: "そのなまけた猫は午後じゅう眠っていた。" },
  { no:   85, en: "gentle", ja: "優しい／穏やかな", kana: "やさしい", ex: "The nurse spoke in a gentle voice.", exja: "その看護師は優しい声で話した。" },
  { no:   86, en: "calm", ja: "落ち着いた／〜を静める", kana: "おちついた", ex: "Try to stay calm during the test.", exja: "試験の間は落ち着いていなさい。" },
  { no:   87, en: "nerve", ja: "神経／度胸", kana: "しんけい", ex: "The cold air hurt the nerves in my teeth.", exja: "冷たい空気が歯の神経にしみた。" },
  { no:   87, en: "nervous", ja: "緊張した／不安な", kana: "きんちょうした", ex: "I felt nervous before my speech.", exja: "私はスピーチの前に緊張した。" },
  { no:   88, en: "exhausted", ja: "疲れ果てた", kana: "つかれはてた", ex: "After the long walk, we were exhausted.", exja: "長い道のりを歩いたあと、私たちは疲れ果てていた。" },
  { no:   88, en: "weary", ja: "くたびれた／うんざりした", kana: "くたびれた", ex: "The weary travelers sat down beside the road.", exja: "くたびれた旅人たちは道ばたに座った。" },
  { no:   89, en: "income", ja: "収入", kana: "しゅうにゅう", ex: "His income is smaller than he hoped.", exja: "彼の収入は望んだよりも少ない。" },
  { no:   90, en: "salary", ja: "給料", kana: "きゅうりょう", ex: "She saves part of her salary every month.", exja: "彼女は毎月、給料の一部を貯金している。" },
  { no:   90, en: "wage", ja: "賃金", kana: "ちんぎん", ex: "The workers asked for higher wages.", exja: "労働者たちはより高い賃金を求めた。" },

  { no:   91, en: "popular", ja: "人気のある", kana: "にんきのある", ex: "That song is popular among high school students.", exja: "あの歌は高校生の間で人気がある。" },
  { no:   91, en: "population", ja: "人口", kana: "じんこう", ex: "The population of this town is falling slowly.", exja: "この町の人口は少しずつ減っている。" },
  { no:   92, en: "cost", ja: "費用／〜がかかる", kana: "ひよう", ex: "The cost of the trip was higher than we thought.", exja: "旅行の費用は思ったより高かった。" },
  { no:   92, en: "costly", ja: "高価な／犠牲の大きい", kana: "こうかな", ex: "Repairing the old roof was costly.", exja: "古い屋根の修理は高価だった。" },
  { no:   93, en: "risk", ja: "危険性／恐れ", kana: "きけんせい", ex: "There is a risk of heavy rain tomorrow.", exja: "明日は大雨の恐れがある。" },
  { no:   93, en: "risky", ja: "あぶない／危険を伴う", kana: "あぶない", ex: "Climbing that rock alone is risky.", exja: "あの岩に一人で登るのはあぶない。" },
  { no:   94, en: "satisfaction", ja: "満足", kana: "まんぞく", ex: "He looked at his work with satisfaction.", exja: "彼は満足して自分の作品を眺めた。" },
  { no:   94, en: "satisfactory", ja: "十分な／満足のいく", kana: "じゅうぶんな", ex: "Her test results were satisfactory this time.", exja: "今回の彼女の試験の結果は十分なものだった。" },
  { no:   94, en: "satisfied", ja: "満足した", kana: "まんぞくした", ex: "The customers were satisfied with the meal.", exja: "客たちはその食事に満足した。" },
  { no:   94, en: "satisfying", ja: "満ち足りた／満足させる", kana: "みちたりた", ex: "Finishing the project was a satisfying experience.", exja: "その企画をやり遂げたのは満ち足りた経験だった。" },
  { no:   95, en: "pleasant", ja: "快い／感じのよい", kana: "こころよい", ex: "We spent a pleasant afternoon in the park.", exja: "私たちは公園で快い午後を過ごした。" },
  { no:   95, en: "please", ja: "〜を喜ばせる", kana: "よろこばせる", ex: "The small gift pleased my little brother.", exja: "その小さな贈り物は弟を喜ばせた。" },
  { no:   95, en: "pleased", ja: "うれしく思う／喜んだ", kana: "うれしい", ex: "She was pleased to hear from her old friend.", exja: "彼女は昔の友人から便りがあってうれしかった。" },
  { no:   96, en: "bored", ja: "退屈した", kana: "たいくつした", ex: "The children got bored during the long speech.", exja: "子どもたちは長い話の間に退屈した。" },
  { no:   96, en: "boredom", ja: "退屈さ", kana: "たいくつさ", ex: "He read old magazines out of boredom.", exja: "彼は退屈さから古い雑誌を読んだ。" },
  { no:   96, en: "boring", ja: "つまらない／退屈な", kana: "つまらない", ex: "The movie was long and boring.", exja: "その映画は長くてつまらなかった。" },
  { no:   97, en: "confused", ja: "混乱した／当惑した", kana: "こんらんした", ex: "I was confused by the strange map.", exja: "私はその奇妙な地図に混乱した。" },
  { no:   97, en: "confusing", ja: "分かりにくい／紛らわしい", kana: "わかりにくい", ex: "The instructions were confusing to everyone.", exja: "その説明は誰にとっても分かりにくかった。" },
  { no:   97, en: "confusion", ja: "混乱", kana: "こんらん", ex: "There was confusion at the station after the accident.", exja: "事故のあと、駅は混乱していた。" },
  { no:   98, en: "scare", ja: "〜を怖がらせる", kana: "こわがらせる", ex: "The loud thunder scared the baby.", exja: "大きな雷は赤ん坊を怖がらせた。" },
  { no:   98, en: "scared", ja: "おびえた／怖がった", kana: "おびえた", ex: "The scared puppy hid under the sofa.", exja: "おびえた子犬はソファの下に隠れた。" },
  { no:   98, en: "scary", ja: "怖い／恐ろしい", kana: "こわい", ex: "We watched a scary movie last night.", exja: "私たちは昨夜、怖い映画を見た。" },
  { no:   99, en: "embarrassed", ja: "恥ずかしい／きまり悪い", kana: "はずかしい", ex: "He was embarrassed when he forgot her name.", exja: "彼は彼女の名前を忘れて恥ずかしかった。" },
  { no:   99, en: "embarrassing", ja: "気まずい／恥ずかしくさせる", kana: "きまずい", ex: "That was an embarrassing moment for all of us.", exja: "あれは私たち全員にとって気まずい瞬間だった。" },
  { no:   99, en: "embarrassment", ja: "当惑／きまり悪さ", kana: "とうわく", ex: "Her face turned red with embarrassment.", exja: "彼女の顔は当惑で赤くなった。" },
  { no:  100, en: "disappointed", ja: "がっかりした／失望した", kana: "がっかりした", ex: "I was disappointed with the final result.", exja: "私は最終の結果にがっかりした。" },
  { no:  100, en: "disappointing", ja: "期待外れの", kana: "きたいはずれ", ex: "The concert was disappointing to many fans.", exja: "そのコンサートは多くのファンにとって期待外れだった。" },
  { no:  100, en: "disappointment", ja: "失望／落胆", kana: "しつぼう", ex: "He could not hide his disappointment.", exja: "彼は失望を隠すことができなかった。" },

  { no:  101, en: "variety", ja: "多様性／さまざまな種類", kana: "たようせい", ex: "The shop sells a wide variety of fresh fruits.", exja: "その店は実にさまざまな新鮮な果物を売っている。" },
  { no:  101, en: "various", ja: "さまざまな／いろいろな", kana: "さまざまな", ex: "Students come to this club for various reasons.", exja: "生徒たちはさまざまな理由でこのクラブに来る。" },
  { no:  102, en: "irregular", ja: "不規則な／不ぞろいな", kana: "ふきそくな", ex: "His sleeping hours have been irregular these days.", exja: "最近、彼の睡眠時間は不規則だ。" },
  { no:  102, en: "regular", ja: "規則正しい／定期的な", kana: "きそくただしい", ex: "She takes a regular walk before breakfast.", exja: "彼女は朝食前に定期的に散歩をする。" },
  { no:  103, en: "pale", ja: "青白い／色が薄い", kana: "あおじろい", ex: "You look pale, so you should rest a little.", exja: "顔が青白いよ。少し休んだほうがいい。" },
  { no:  104, en: "ugly", ja: "醜い／見苦しい", kana: "みにくい", ex: "The old factory looked ugly after the fire.", exja: "その古い工場は火事のあと見苦しく見えた。" },
  { no:  105, en: "delicate", ja: "繊細な／壊れやすい", kana: "せんさいな", ex: "She has a delicate sense of color.", exja: "彼女は色に対する繊細な感覚を持っている。" },
  { no:  106, en: "flexibility", ja: "柔軟性／しなやかさ", kana: "じゅうなんせい", ex: "Daily stretching improves the flexibility of your body.", exja: "毎日のストレッチは体の柔軟性を高める。" },
  { no:  106, en: "flexible", ja: "柔軟な／融通のきく", kana: "じゅうなんな", ex: "Our teacher is flexible about the deadline.", exja: "私たちの先生は締め切りについて柔軟だ。" },
  { no:  107, en: "tidy", ja: "きちんとした／整った", kana: "きちんとした", ex: "He keeps his desk tidy every day.", exja: "彼は毎日、机をきちんと整えている。" },
  { no:  108, en: "plain", ja: "質素な／分かりやすい", kana: "しっそな", ex: "She wore a plain white dress to the party.", exja: "彼女はパーティーに質素な白い服を着ていった。" },
  { no:  109, en: "rough", ja: "粗い／荒々しい", kana: "あらい", ex: "The surface of this stone feels rough.", exja: "この石の表面は粗い感じがする。" },
  { no:  109, en: "roughly", ja: "おおよそ／乱暴に", kana: "おおよそ", ex: "The trip takes roughly three hours by bus.", exja: "その旅はバスでおおよそ3時間かかる。" },
  { no:  109, en: "smooth", ja: "なめらかな／順調な", kana: "なめらかな", ex: "The baby's skin is very smooth.", exja: "赤ちゃんの肌はとてもなめらかだ。" },
  { no:  110, en: "flat", ja: "平らな／平たい", kana: "たいらな", ex: "We put our tent on flat ground.", exja: "私たちは平らな地面にテントを張った。" },

  { no:  111, en: "empty", ja: "空の／人のいない", kana: "からっぽ", ex: "The box was empty when I opened it.", exja: "箱を開けたとき、中は空っぽだった。" },
  { no:  112, en: "even", ja: "均等な／〜でさえ", kana: "きんとうな", ex: "We divided the cake into even pieces.", exja: "私たちはケーキを均等な大きさに分けた。" },
  { no:  112, en: "uneven", ja: "でこぼこの／不均等な", kana: "でこぼこ", ex: "The old road is uneven, so drive slowly.", exja: "その古い道はでこぼこなので、ゆっくり運転して。" },
  { no:  113, en: "broad", ja: "幅の広い／範囲の広い", kana: "はばひろい", ex: "A broad river runs through this town.", exja: "幅の広い川がこの町を流れている。" },
  { no:  113, en: "narrow", ja: "狭い／細い", kana: "せまい", ex: "We walked along a narrow path in the woods.", exja: "私たちは森の細い小道を歩いた。" },
  { no:  113, en: "wide", ja: "広い／幅のある", kana: "ひろい", ex: "The garden is wide enough for a soccer game.", exja: "その庭はサッカーをするのに十分広い。" },
  { no:  114, en: "deep", ja: "深い／深刻な", kana: "ふかい", ex: "This lake is deeper than it looks.", exja: "この湖は見た目よりも深い。" },
  { no:  114, en: "shallow", ja: "浅い／浅はかな", kana: "あさい", ex: "Children can play safely in the shallow water.", exja: "子どもたちは浅い水の中で安全に遊べる。" },
  { no:  115, en: "dense", ja: "密集した／濃い", kana: "みっしゅうした", ex: "A dense forest covers the northern hills.", exja: "密集した森が北の丘を覆っている。" },
  { no:  115, en: "thick", ja: "厚い／太い", kana: "あつい", ex: "He read a thick book during the holidays.", exja: "彼は休みの間に厚い本を読んだ。" },
  { no:  116, en: "thin", ja: "薄い／やせた", kana: "うすい", ex: "Cut the bread into thin slices, please.", exja: "パンを薄く切ってください。" },
  { no:  117, en: "huge", ja: "巨大な／ばく大な", kana: "きょだいな", ex: "A huge ship entered the harbor this morning.", exja: "巨大な船が今朝、港に入ってきた。" },
  { no:  118, en: "tiny", ja: "ごく小さい／わずかな", kana: "ごくちいさい", ex: "A tiny bird was sitting on the wire.", exja: "ごく小さな鳥が電線にとまっていた。" },
  { no:  119, en: "careful", ja: "注意深い／慎重な", kana: "ちゅういぶかい", ex: "Be careful when you cross this street.", exja: "この通りを渡るときは注意しなさい。" },
  { no:  119, en: "careless", ja: "不注意な／うっかりした", kana: "ふちゅういな", ex: "His careless mistake broke the machine.", exja: "彼の不注意なミスが機械を壊した。" },
  { no:  120, en: "mistake", ja: "間違い／誤り", kana: "まちがい", ex: "I made a small mistake in the calculation.", exja: "私は計算で小さな間違いをした。" },

  { no:  121, en: "earn", ja: "〜を稼ぐ／〜を得る", kana: "かせぐ", ex: "She earns money by teaching piano.", exja: "彼女はピアノを教えてお金を稼いでいる。" },
  { no:  121, en: "earnings", ja: "収入／もうけ", kana: "しゅうにゅう", ex: "He saved half of his earnings last year.", exja: "彼は昨年、収入の半分を貯金した。" },
  { no:  123, en: "crowd", ja: "群衆／人混み", kana: "ぐんしゅう", ex: "A large crowd waited in front of the gate.", exja: "大きな群衆が門の前で待っていた。" },
  { no:  124, en: "gather", ja: "〜を集める／集まる", kana: "あつめる", ex: "The students gathered in the gym at noon.", exja: "生徒たちは正午に体育館に集まった。" },
  { no:  125, en: "ability", ja: "能力／才能", kana: "のうりょく", ex: "She has the ability to solve hard problems.", exja: "彼女は難しい問題を解く能力がある。" },
  { no:  125, en: "able", ja: "〜することができる", kana: "できる", ex: "I was able to finish the report last night.", exja: "私は昨夜、その報告書を終えることができた。" },
  { no:  125, en: "disability", ja: "障害／不自由", kana: "しょうがい", ex: "This museum is designed for people with a disability.", exja: "この博物館は障害のある人のために設計されている。" },
  { no:  126, en: "courage", ja: "勇気／度胸", kana: "ゆうき", ex: "It took courage to speak in front of everyone.", exja: "みんなの前で話すには勇気が必要だった。" },
  { no:  127, en: "duty", ja: "義務／務め", kana: "ぎむ", ex: "It is our duty to protect this river.", exja: "この川を守ることは私たちの義務だ。" },
  { no:  128, en: "attempt", ja: "試み／〜を試みる", kana: "こころみる", ex: "He made a second attempt to climb the wall.", exja: "彼は壁を登ろうと2度目の試みをした。" },
  { no:  129, en: "tend", ja: "〜する傾向がある", kana: "けいこうがある", ex: "People tend to eat more when they are tired.", exja: "人は疲れているとより多く食べる傾向がある。" },
  { no:  129, en: "tendency", ja: "傾向／性質", kana: "けいこう", ex: "He has a tendency to forget people's names.", exja: "彼には人の名前を忘れる癖がある。" },
  { no:  130, en: "struggle", ja: "奮闘する／もがく", kana: "もがく", ex: "She struggled to open the heavy door.", exja: "彼女は重い扉を開けようと必死になった。" },

  { no:  131, en: "mend", ja: "〜を繕う／〜を直す", kana: "つくろう", ex: "My grandmother mended my torn shirt.", exja: "祖母が破れたシャツを繕ってくれた。" },
  { no:  131, en: "repair", ja: "〜を修理する", kana: "しゅうりする", ex: "They repaired the roof before the rainy season.", exja: "彼らは梅雨の前に屋根を修理した。" },
  { no:  132, en: "fix", ja: "〜を直す／〜を固定する", kana: "なおす", ex: "Can you fix my bicycle by Friday?", exja: "金曜日までに私の自転車を直せますか。" },
  { no:  133, en: "handle", ja: "〜を扱う／取っ手", kana: "あつかう", ex: "She handles difficult customers very calmly.", exja: "彼女は難しい客をとても落ち着いて扱う。" },
  { no:  134, en: "operate", ja: "〜を操作する／手術する", kana: "そうさする", ex: "Only trained staff may operate this machine.", exja: "訓練を受けた職員だけがこの機械を操作できる。" },
  { no:  134, en: "operation", ja: "手術／操作／作戦", kana: "しゅじゅつ", ex: "The operation on his knee went well.", exja: "彼のひざの手術はうまくいった。" },
  { no:  135, en: "remain", ja: "残る／〜のままである", kana: "のこる", ex: "Only two cookies remained on the plate.", exja: "皿の上には2枚のクッキーしか残っていなかった。" },
  { no:  136, en: "leave", ja: "〜を去る／〜を置き忘れる", kana: "さる", ex: "We must leave the station before six.", exja: "私たちは6時前に駅を出なければならない。" },
  { no:  137, en: "continue", ja: "〜を続ける／続く", kana: "つづける", ex: "The rain continued all through the night.", exja: "雨は一晩中降り続いた。" },
  { no:  137, en: "continuous", ja: "絶え間ない／連続した", kana: "たえまない", ex: "The continuous noise made it hard to study.", exja: "絶え間ない騒音のせいで勉強しにくかった。" },
  { no:  138, en: "last", ja: "続く／最後の", kana: "つづく", ex: "The concert lasted almost three hours.", exja: "そのコンサートはほぼ3時間続いた。" },
  { no:  139, en: "scold", ja: "〜をしかる", kana: "しかる", ex: "His father scolded him for coming home late.", exja: "彼の父は帰宅が遅いことで彼をしかった。" },
  { no:  140, en: "punish", ja: "〜を罰する", kana: "ばっする", ex: "The school punished the students who cheated.", exja: "学校は不正をした生徒たちを罰した。" },
  { no:  140, en: "punishment", ja: "罰／処罰", kana: "しょばつ", ex: "Losing his phone for a week was a fair punishment.", exja: "1週間電話を取り上げられたのは妥当な処罰だった。" },

  { no:  141, en: "blame", ja: "〜を責める／責任", kana: "せめる", ex: "Don't blame your brother for the broken cup.", exja: "割れたカップのことで弟を責めてはいけない。" },
  { no:  142, en: "fault", ja: "責任／過失／欠点", kana: "せきにん", ex: "The accident was not entirely my fault.", exja: "その事故は全部が私の責任というわけではなかった。" },
  { no:  143, en: "award", ja: "賞／〜を授与する", kana: "しょう", ex: "She received an award for her science project.", exja: "彼女は理科の研究で賞を受けた。" },
  { no:  143, en: "prize", ja: "賞品／賞金", kana: "しょうひん", ex: "He won first prize in the speech contest.", exja: "彼はスピーチ大会で一等賞を取った。" },
  { no:  144, en: "reward", ja: "報酬／ほうび", kana: "ほうしゅう", ex: "They offered a reward for finding the lost dog.", exja: "彼らは迷子の犬を見つけた人に報酬を出した。" },
  { no:  145, en: "wrap", ja: "〜を包む", kana: "つつむ", ex: "She wrapped the gift in blue paper.", exja: "彼女は贈り物を青い紙で包んだ。" },
  { no:  146, en: "pack", ja: "〜を詰める／荷造りする", kana: "につくりする", ex: "I packed my bag the night before the trip.", exja: "私は旅行の前の晩にかばんの荷造りをした。" },
  { no:  146, en: "unpack", ja: "荷をほどく／中身を出す", kana: "ほどく", ex: "He unpacked his suitcase as soon as he arrived.", exja: "彼は着くとすぐに旅行かばんの荷をほどいた。" },
  { no:  147, en: "custom", ja: "慣習／しきたり", kana: "かんしゅう", ex: "Bowing is an old custom in this country.", exja: "おじぎはこの国の古い慣習だ。" },
  { no:  148, en: "habit", ja: "習慣／癖", kana: "しゅうかん", ex: "Reading before bed is a good habit.", exja: "寝る前に本を読むのは良い習慣だ。" },
  { no:  149, en: "match", ja: "試合／〜に合う", kana: "しあい", ex: "The tennis match was postponed because of rain.", exja: "テニスの試合は雨で延期された。" },
  { no:  150, en: "fit", ja: "〜にぴったり合う／適する", kana: "ぴったりあう", ex: "These shoes fit my feet perfectly.", exja: "この靴は私の足にぴったり合う。" },

  { no:  151, en: "suit", ja: "〜に似合う／都合が合う", kana: "にあう", ex: "That blue jacket suits you very well.", exja: "その青い上着はあなたにとてもよく似合う。" },
  { no:  151, en: "suitable", ja: "ふさわしい／適した", kana: "ふさわしい", ex: "This film is not suitable for small children.", exja: "この映画は小さな子どもにはふさわしくない。" },
  { no:  152, en: "manner", ja: "やり方／態度", kana: "やりかた", ex: "He answered in a friendly manner.", exja: "彼は親しみのあるやり方で答えた。" },
  { no:  152, en: "manners", ja: "礼儀作法／行儀", kana: "れいぎさほう", ex: "Good table manners matter at a formal dinner.", exja: "正式な夕食では食事の礼儀作法が大切だ。" },
  { no:  153, en: "arm", ja: "腕", kana: "うで", ex: "He broke his left arm while skiing.", exja: "彼はスキー中に左腕を折った。" },
  { no:  153, en: "arms", ja: "武器／兵器", kana: "へいき", ex: "The country agreed to reduce its arms.", exja: "その国は兵器を減らすことに同意した。" },
  { no:  154, en: "glass", ja: "ガラス／コップ", kana: "こっぷ", ex: "She poured milk into a tall glass.", exja: "彼女は背の高いコップに牛乳を注いだ。" },
  { no:  154, en: "glasses", ja: "めがね", kana: "めがね", ex: "I cannot read the sign without my glasses.", exja: "めがねがないとその標識が読めない。" },
  { no:  156, en: "reach", ja: "〜に着く／手を伸ばす", kana: "とうちゃくする", ex: "We reached the top of the hill at sunset.", exja: "私たちは日没に丘の頂上に着いた。" },
  { no:  157, en: "discuss", ja: "〜について話し合う", kana: "はなしあう", ex: "The class discussed the problem for an hour.", exja: "クラスはその問題について1時間話し合った。" },
  { no:  157, en: "discussion", ja: "議論／話し合い", kana: "ぎろん", ex: "Their discussion about the trip went on late.", exja: "旅行についての彼らの議論は遅くまで続いた。" },
  { no:  158, en: "contact", ja: "連絡／〜と連絡を取る", kana: "れんらく", ex: "Please contact me if the train is late.", exja: "電車が遅れたら私に連絡してください。" },
  { no:  159, en: "approach", ja: "〜に近づく／取り組み方", kana: "ちかづく", ex: "A small boat approached the island slowly.", exja: "小さな船がゆっくりと島に近づいた。" },
  { no:  160, en: "resemble", ja: "〜に似ている", kana: "にている", ex: "She resembles her mother in many ways.", exja: "彼女は多くの点で母親に似ている。" },

  { no:  161, en: "lend", ja: "〜を貸す／〜を貸し出す", kana: "かしだす", ex: "Could you lend me your umbrella today?", exja: "今日、傘を貸してもらえますか。" },
  { no:  162, en: "borrow", ja: "〜を借りる", kana: "かりる", ex: "I borrowed two books from the library.", exja: "私は図書館で本を2冊借りた。" },
  { no:  163, en: "rent", ja: "家賃／〜を賃借りする", kana: "やちん", ex: "They rent a small house near the sea.", exja: "彼らは海の近くの小さな家を借りている。" },
  { no:  163, en: "rental", ja: "賃貸／貸し出し", kana: "ちんたい", ex: "The rental of the hall costs ten thousand yen.", exja: "そのホールの賃貸料は1万円かかる。" },
  { no:  164, en: "loan", ja: "貸付／借金", kana: "かしつけ", ex: "He took out a loan to buy a new car.", exja: "彼は新しい車を買うために貸付を受けた。" },
  { no:  166, en: "direct", ja: "直接の／〜を指揮する", kana: "ちょくせつの", ex: "There is a direct flight from Tokyo to Rome.", exja: "東京からローマへの直行便がある。" },
  { no:  166, en: "director", ja: "監督／取締役", kana: "かんとく", ex: "The director asked the actors to try again.", exja: "監督は俳優たちにもう一度やるよう頼んだ。" },
  { no:  166, en: "indirect", ja: "間接的な／遠回しな", kana: "かんせつてきな", ex: "She gave an indirect answer to my question.", exja: "彼女は私の質問に間接的な答えをした。" },
  { no:  167, en: "impatient", ja: "我慢できない／いらだった", kana: "がまんできない", ex: "The children grew impatient while waiting for the bus.", exja: "子どもたちはバスを待つ間に我慢できなくなった。" },
  { no:  167, en: "patience", ja: "忍耐／我慢強さ", kana: "にんたい", ex: "Learning a language takes a lot of patience.", exja: "言葉を学ぶには多くの忍耐が必要だ。" },
  { no:  167, en: "patient", ja: "患者／忍耐強い", kana: "かんじゃ", ex: "The doctor visited every patient in the room.", exja: "医師は部屋のすべての患者を訪ねた。" },
  { no:  168, en: "tear", ja: "涙／〜を引き裂く", kana: "なみだ", ex: "Tears ran down her face during the movie.", exja: "映画の間、涙が彼女の顔を流れ落ちた。" },
  { no:  169, en: "notable", ja: "注目すべき／著名な", kana: "ちゅうもくすべき", ex: "Her speech was the most notable part of the event.", exja: "彼女の演説はその催しで最も注目すべき部分だった。" },
  { no:  170, en: "shop", ja: "買い物をする／店", kana: "かいものする", ex: "We shopped for vegetables at the morning market.", exja: "私たちは朝市で野菜を買った。" },
  { no:  170, en: "storage", ja: "保管／しまっておくこと", kana: "ほかん", ex: "We keep our winter clothes in storage under the bed.", exja: "私たちは冬服をベッドの下に保管している。" },
  { no:  170, en: "store", ja: "〜を蓄える／店", kana: "たくわえる", ex: "Squirrels store nuts for the winter.", exja: "リスは冬に備えて木の実を蓄える。" },

  { no:  171, en: "admission", ja: "入場／入学の許可", kana: "にゅうじょう", ex: "Admission to the garden is free on Sundays.", exja: "日曜日はその庭園への入場が無料だ。" },
  { no:  171, en: "admit", ja: "〜を認める／入場を許す", kana: "みとめる", ex: "He admitted that he had forgotten the promise.", exja: "彼は約束を忘れていたことを認めた。" },
  { no:  172, en: "fee", ja: "料金／謝礼", kana: "りょうきん", ex: "The club asks for a small fee every month.", exja: "そのクラブは毎月わずかな料金を求める。" },
  { no:  173, en: "tuition", ja: "授業料／指導", kana: "じゅぎょうりょう", ex: "His parents paid the tuition for the first year.", exja: "彼の両親は1年目の授業料を払った。" },
  { no:  174, en: "charge", ja: "〜を請求する／料金", kana: "せいきゅうする", ex: "The garage charged me too much for the work.", exja: "その修理工場は作業代を私に高く請求した。" },
  { no:  175, en: "fare", ja: "運賃", kana: "うんちん", ex: "The bus fare went up again this spring.", exja: "バスの運賃がこの春また上がった。" },
  { no:  176, en: "fine", ja: "罰金／立派な", kana: "ばっきん", ex: "He had to pay a fine for parking there.", exja: "彼はそこに駐車したため罰金を払わねばならなかった。" },
  { no:  177, en: "penalty", ja: "罰則／ばつ", kana: "ばっそく", ex: "There is a heavy penalty for breaking this rule.", exja: "この規則を破ると重い罰則がある。" },
  { no:  178, en: "weather", ja: "天気／天候", kana: "てんき", ex: "The weather changed suddenly in the afternoon.", exja: "午後、天気が急に変わった。" },
  { no:  178, en: "whether", ja: "〜かどうか", kana: "かどうか", ex: "I do not know whether she will come tonight.", exja: "彼女が今夜来るかどうか分からない。" },
  { no:  179, en: "forecast", ja: "予報／〜を予報する", kana: "よほう", ex: "The forecast says it will snow tomorrow.", exja: "予報では明日は雪が降るそうだ。" },
  { no:  180, en: "wind", ja: "風", kana: "かぜ", ex: "A cold wind shook the windows all night.", exja: "冷たい風が一晩中窓を揺らした。" },
  { no:  180, en: "windy", ja: "風の強い", kana: "かぜがつよい", ex: "It was too windy to ride a bicycle.", exja: "風が強すぎて自転車に乗れなかった。" },

  { no:  181, en: "blow", ja: "吹く／〜を吹き飛ばす", kana: "ふきとばす", ex: "The wind is blowing the leaves off the tree.", exja: "風が木から葉を吹き飛ばしている。" },
  { no:  182, en: "typhoon", ja: "台風", kana: "たいふう", ex: "A strong typhoon is moving toward the island.", exja: "強い台風が島に向かって進んでいる。" },
  { no:  183, en: "hit", ja: "〜を襲う／〜を打つ", kana: "おそう", ex: "A huge wave hit the small fishing boat.", exja: "巨大な波が小さな漁船を襲った。" },
  { no:  184, en: "flood", ja: "洪水／〜を水浸しにする", kana: "こうずい", ex: "The heavy rain caused a flood in the village.", exja: "大雨が村に洪水を引き起こした。" },
  { no:  185, en: "warn", ja: "〜に警告する", kana: "けいこくする", ex: "The police warned drivers about the icy road.", exja: "警察は凍った道路について運転者に警告した。" },
  { no:  185, en: "warning", ja: "警告／注意報", kana: "ちゅういほう", ex: "The city issued a warning about heavy snow.", exja: "市は大雪の注意報を出した。" },
  { no:  186, en: "landslide", ja: "土砂崩れ／地すべり", kana: "どしゃくずれ", ex: "A landslide closed the mountain road for days.", exja: "土砂崩れで山道が数日間通れなくなった。" },
  { no:  187, en: "occur", ja: "起こる／生じる", kana: "おこる", ex: "The accident occurred just before midnight.", exja: "その事故は真夜中の直前に起こった。" },
  { no:  187, en: "occurrence", ja: "出来事／発生", kana: "はっせい", ex: "Such a strong quake is a rare occurrence here.", exja: "これほど強い揺れはここでは珍しい出来事だ。" },
  { no:  188, en: "rescue", ja: "〜を救助する", kana: "きゅうじょする", ex: "Firefighters rescued a cat from the tall tree.", exja: "消防士が高い木から猫を救助した。" },
  { no:  189, en: "drown", ja: "おぼれる／おぼれ死ぬ", kana: "おぼれる", ex: "He almost drowned in the deep pool.", exja: "彼は深いプールでおぼれかけた。" },
  { no:  190, en: "atmosphere", ja: "雰囲気／大気", kana: "ふんいき", ex: "This small cafe has a warm atmosphere.", exja: "この小さな喫茶店は温かい雰囲気がある。" },
  { no:  190, en: "mood", ja: "気分／機嫌", kana: "きぶん", ex: "Good music puts my father in a happy mood.", exja: "良い音楽は父を楽しい気分にする。" },

  { no:  191, en: "temperature", ja: "気温／温度／体温", kana: "きおん", ex: "The temperature dropped below zero last night.", exja: "昨夜、気温が0度を下回った。" },
  { no:  192, en: "humid", ja: "湿気の多い／蒸し暑い", kana: "しめっぽい", ex: "Summer in this city is hot and humid.", exja: "この街の夏は暑くて湿気が多い。" },
  { no:  192, en: "humidity", ja: "湿度／湿気", kana: "しつど", ex: "The high humidity made the room uncomfortable.", exja: "高い湿度が部屋を不快にした。" },
  { no:  193, en: "degree", ja: "度／程度／学位", kana: "ていど", ex: "Water boils at one hundred degrees.", exja: "水は100度で沸騰する。" },
  { no:  194, en: "mild", ja: "穏やかな／ひかえめな", kana: "おだやかな", ex: "The winter was unusually mild this year.", exja: "今年の冬は異常に穏やかだった。" },
  { no:  195, en: "lightning", ja: "稲妻／雷光", kana: "いなずま", ex: "Lightning lit up the whole sky for a moment.", exja: "稲妻が一瞬、空全体を照らした。" },
  { no:  195, en: "thunder", ja: "雷／雷鳴", kana: "かみなり", ex: "The thunder woke the baby in the night.", exja: "夜、雷が赤ん坊を起こした。" },
  { no:  196, en: "fog", ja: "霧", kana: "きり", ex: "Thick fog covered the harbor this morning.", exja: "濃い霧が今朝、港を覆った。" },
  { no:  196, en: "foggy", ja: "霧の深い", kana: "きりがふかい", ex: "The road was foggy when we left home.", exja: "家を出たとき、道は霧が深かった。" },
  { no:  197, en: "disaster", ja: "災害／大失敗", kana: "さいがい", ex: "The town is preparing for a natural disaster.", exja: "町は自然災害に備えている。" },
  { no:  197, en: "disastrous", ja: "悲惨な／破滅的な", kana: "ひさんな", ex: "The new plan had a disastrous result.", exja: "その新しい計画は悲惨な結果になった。" },
  { no:  198, en: "earthquake", ja: "地震", kana: "じしん", ex: "A small earthquake shook our house last week.", exja: "先週、小さな地震が私たちの家を揺らした。" },
  { no:  199, en: "volcano", ja: "火山", kana: "かざん", ex: "That volcano has not erupted for two hundred years.", exja: "あの火山は200年間噴火していない。" },
  { no:  200, en: "storm", ja: "嵐／暴風雨", kana: "あらし", ex: "The storm knocked down several old trees.", exja: "嵐が何本かの古い木を倒した。" },
  { no:  200, en: "stormy", ja: "荒れ模様の／嵐の", kana: "あれもよう", ex: "They canceled the ferry because of stormy seas.", exja: "荒れた海のためフェリーは欠航になった。" },

  { no:  201, en: "ocean", ja: "海／海洋", kana: "かいよう", ex: "The ocean looked calm from our hotel window.", exja: "海はホテルの窓から穏やかに見えた。" },
  { no:  202, en: "continent", ja: "大陸", kana: "たいりく", ex: "Africa is a continent with more than fifty countries.", exja: "アフリカは五十を超える国がある大陸だ。" },
  { no:  202, en: "land", ja: "陸地／土地", kana: "りくち", ex: "After three weeks at sea, the sailors finally saw land.", exja: "三週間の航海の後、船員たちはついに陸地を見つけた。" },
  { no:  203, en: "island", ja: "島／小島", kana: "こじま", ex: "We took a small boat to the island every summer.", exja: "私たちは毎年夏に小さな船でその島へ渡った。" },
  { no:  204, en: "desert", ja: "砂漠／〜を見捨てる", kana: "さばく", ex: "Only a few tough plants grow in this dry desert.", exja: "この乾いた砂漠には丈夫な植物がわずかに育つだけだ。" },
  { no:  204, en: "dessert", ja: "食後の甘い物／デザート", kana: "あまいもの", ex: "My sister ordered ice cream for dessert.", exja: "妹はデザートにアイスクリームを注文した。" },
  { no:  205, en: "valley", ja: "谷／渓谷", kana: "けいこく", ex: "A clear river runs through the quiet valley.", exja: "澄んだ川が静かな谷を流れている。" },
  { no:  206, en: "tropical", ja: "熱帯の", kana: "ねったいの", ex: "We saw many tropical birds during the boat trip.", exja: "船の旅の間に私たちは熱帯の鳥をたくさん見た。" },
  { no:  207, en: "climate", ja: "気候", kana: "きこう", ex: "The climate of this island is mild all year.", exja: "この島の気候は一年中穏やかだ。" },
  { no:  208, en: "human", ja: "人間／人間の", kana: "にんげん", ex: "No other animal builds cities the way a human does.", exja: "人間のように都市を築く動物は他にいない。" },
  { no:  209, en: "evolution", ja: "進化", kana: "しんか", ex: "This museum explains the evolution of birds.", exja: "この博物館は鳥の進化を説明している。" },
  { no:  209, en: "evolutionary", ja: "進化上の／進化に関する", kana: "しんかじょうの", ex: "Wings gave birds a great evolutionary advantage.", exja: "翼は鳥に大きな進化上の利点を与えた。" },
  { no:  209, en: "evolve", ja: "進化する／発展する", kana: "はってんする", ex: "Languages evolve slowly over hundreds of years.", exja: "言語は何百年もかけてゆっくりと変化していく。" },
  { no:  210, en: "survival", ja: "生存／生き残ること", kana: "せいぞん", ex: "Clean water is necessary for survival in the mountains.", exja: "山では生存にきれいな水が欠かせない。" },
  { no:  210, en: "survive", ja: "生き延びる", kana: "いきのびる", ex: "Only two old trees survived the terrible fire.", exja: "ひどい火事を生き延びたのは古い木が二本だけだった。" },

  { no:  211, en: "revival", ja: "復活／再興", kana: "ふっかつ", ex: "The town festival had a surprising revival last spring.", exja: "その町の祭りは昨春に驚くような復活を遂げた。" },
  { no:  211, en: "revive", ja: "生き返る／〜を復活させる", kana: "いきかえる", ex: "A cup of hot tea revived me after the cold walk.", exja: "寒い中を歩いた後、熱いお茶で生き返った。" },
  { no:  212, en: "damage", ja: "損害／〜に損害を与える", kana: "そんがい", ex: "The storm did serious damage to the school roof.", exja: "嵐は学校の屋根に深刻な損害を与えた。" },
  { no:  213, en: "environment", ja: "環境", kana: "かんきょう", ex: "We must protect the environment for our children.", exja: "私たちは子どもたちのために環境を守らなければならない。" },
  { no:  213, en: "environmental", ja: "環境の", kana: "かんきょうの", ex: "She joined an environmental club at her new school.", exja: "彼女は新しい学校で環境クラブに入った。" },
  { no:  213, en: "surroundings", ja: "周囲の様子／環境", kana: "まわり", ex: "The lost cat studied its new surroundings carefully.", exja: "迷い猫は新しい周囲の様子を注意深く見ていた。" },
  { no:  214, en: "spoil", ja: "〜を台なしにする／甘やかす", kana: "だいなしにする", ex: "Heavy rain spoiled our picnic on Sunday.", exja: "大雨が日曜のピクニックを台なしにした。" },
  { no:  214, en: "spoiled", ja: "甘やかされた／だめになった", kana: "あまやかされた", ex: "The spoiled boy never helps with the dishes.", exja: "その甘やかされた少年は皿洗いを決して手伝わない。" },
  { no:  215, en: "view", ja: "眺め／見方", kana: "ながめ", ex: "The view from the top of the hill was wonderful.", exja: "丘の上からの眺めはすばらしかった。" },
  { no:  216, en: "save", ja: "〜を救う／蓄える", kana: "すくう", ex: "He saved a little girl from the cold river.", exja: "彼は冷たい川から幼い少女を救った。" },
  { no:  217, en: "energetic", ja: "活動的な／元気いっぱいの", kana: "かつどうてきな", ex: "Our new coach is young and energetic.", exja: "新しいコーチは若くて活動的だ。" },
  { no:  217, en: "energy", ja: "力／活力", kana: "かつりょく", ex: "Climbing the stairs uses more energy than you think.", exja: "階段を上るのは思っている以上に力を使う。" },
  { no:  218, en: "poison", ja: "毒／毒物", kana: "どくぶつ", ex: "Some pretty mushrooms contain a strong poison.", exja: "きれいなキノコの中には強い毒を持つものがある。" },
  { no:  218, en: "poisonous", ja: "有毒な", kana: "ゆうどくな", ex: "Never touch that poisonous snake in the grass.", exja: "草むらのあの有毒なヘビには決して触るな。" },
  { no:  219, en: "substance", ja: "物質", kana: "ぶっしつ", ex: "The scientist found a strange substance in the water.", exja: "科学者は水の中に奇妙な物質を見つけた。" },
  { no:  220, en: "chemical", ja: "化学薬品／化学の", kana: "かがくやくひん", ex: "Some farmers use fewer chemicals on their vegetables.", exja: "野菜に使う化学薬品を減らしている農家もいる。" },

  { no:  221, en: "pollutant", ja: "汚染物質", kana: "おせんぶっしつ", ex: "Old buses send many pollutants into the city air.", exja: "古いバスは多くの汚染物質を街の空気に出す。" },
  { no:  221, en: "pollute", ja: "〜を汚染する／汚す", kana: "よごす", ex: "That factory polluted the river for thirty years.", exja: "あの工場は三十年間その川を汚染した。" },
  { no:  221, en: "pollution", ja: "汚染／公害", kana: "こうがい", ex: "Air pollution is a serious problem in big cities.", exja: "大気汚染は大都市の深刻な問題だ。" },
  { no:  222, en: "garbage", ja: "生ごみ／くず", kana: "なまごみ", ex: "Please take the garbage out before dinner.", exja: "夕食の前にごみを出しておいて。" },
  { no:  222, en: "rubbish", ja: "ごみ／がらくた", kana: "がらくた", ex: "He threw the rubbish into a big paper box.", exja: "彼はがらくたを大きな紙箱に投げ入れた。" },
  { no:  223, en: "litter", ja: "散らかったごみ／〜を散らかす", kana: "ちらかす", ex: "Visitors must not litter in this quiet park.", exja: "来園者はこの静かな公園でごみを散らかしてはいけない。" },
  { no:  223, en: "trash", ja: "くず／ごみ", kana: "ごみくず", ex: "The trash can beside the door is already full.", exja: "ドアの横のごみ箱はもういっぱいだ。" },
  { no:  224, en: "supply", ja: "供給／〜を供給する", kana: "きょうきゅう", ex: "The village has a good supply of clean water.", exja: "その村にはきれいな水の供給が十分にある。" },
  { no:  225, en: "electric", ja: "電気の", kana: "でんきの", ex: "My father finally bought an electric bicycle.", exja: "父はついに電気自転車を買った。" },
  { no:  225, en: "electricity", ja: "電気", kana: "でんき", ex: "The storm cut off our electricity for six hours.", exja: "嵐で六時間電気が止まった。" },
  { no:  226, en: "reduce", ja: "〜を減らす", kana: "へらす", ex: "We should reduce the plastic we use every day.", exja: "私たちは毎日使うプラスチックを減らすべきだ。" },
  { no:  226, en: "reduction", ja: "削減／減少", kana: "さくげん", ex: "The company announced a reduction in ticket prices.", exja: "その会社はチケット価格の引き下げを発表した。" },
  { no:  227, en: "waist", ja: "腰／腰回り", kana: "こしまわり", ex: "He tied a thick rope around his waist.", exja: "彼は太いロープを腰に巻きつけた。" },
  { no:  227, en: "waste", ja: "〜を無駄にする／廃棄物", kana: "むだにする", ex: "Don't waste time on your phone before the exam.", exja: "試験の前にスマホで時間を無駄にするな。" },
  { no:  228, en: "burn", ja: "燃える／〜を燃やす", kana: "もえる", ex: "The dry leaves burned very quickly.", exja: "乾いた葉はあっという間に燃えた。" },
  { no:  229, en: "fossil", ja: "化石", kana: "かせき", ex: "They found a small fish fossil inside the rock.", exja: "彼らは岩の中に小さな魚の化石を見つけた。" },
  { no:  230, en: "fuel", ja: "燃料", kana: "ねんりょう", ex: "The plane needs extra fuel for such a long flight.", exja: "その飛行機は長い飛行のために余分な燃料が必要だ。" },

  { no:  231, en: "lunar", ja: "月の", kana: "つきの", ex: "A lunar month is about twenty-nine days long.", exja: "太陰月はおよそ二十九日の長さだ。" },
  { no:  231, en: "solar", ja: "太陽の", kana: "たいようの", ex: "Our school put solar panels on the gym roof.", exja: "私たちの学校は体育館の屋根に太陽光パネルを設置した。" },
  { no:  231, en: "sun", ja: "太陽", kana: "たいよう", ex: "The sun rose slowly behind the eastern mountains.", exja: "太陽は東の山の向こうからゆっくり昇った。" },
  { no:  232, en: "generate", ja: "〜を生み出す", kana: "うみだす", ex: "Wind can generate electricity without any smoke.", exja: "風は煙を出さずに電気を生み出すことができる。" },
  { no:  232, en: "generation", ja: "世代", kana: "せだい", ex: "My grandmother's generation lived through hard times.", exja: "祖母の世代は苦しい時代を生き抜いた。" },
  { no:  232, en: "generator", ja: "発電機", kana: "はつでんき", ex: "The hospital used a generator during the power cut.", exja: "病院は停電の間、発電機を使った。" },
  { no:  233, en: "greenhouse", ja: "温室", kana: "おんしつ", ex: "Tomatoes grow well inside this warm greenhouse.", exja: "トマトはこの暖かい温室の中でよく育つ。" },
  { no:  234, en: "resource", ja: "資源", kana: "しげん", ex: "Japan has few natural resources of its own.", exja: "日本には自国の天然資源が乏しい。" },
  { no:  234, en: "source", ja: "源／出所", kana: "みなもと", ex: "The source of this river is high in the mountains.", exja: "この川の源は山の高いところにある。" },
  { no:  235, en: "material", ja: "材料／素材", kana: "ざいりょう", ex: "We need soft material to make these dolls.", exja: "この人形を作るには柔らかい材料が必要だ。" },
  { no:  238, en: "soon", ja: "まもなく／すぐに", kana: "まもなく", ex: "The last train will leave soon, so hurry up.", exja: "終電はまもなく出るから急いで。" },
  { no:  242, en: "nowadays", ja: "近頃／最近では", kana: "ちかごろ", ex: "Nowadays many students study with tablets.", exja: "近頃は多くの生徒がタブレットで勉強する。" },
  { no:  246, en: "past", ja: "過去／昔", kana: "むかし", ex: "Forget the past and think about tomorrow.", exja: "過去は忘れて明日のことを考えよう。" },
  { no:  247, en: "future", ja: "未来／将来", kana: "みらい", ex: "She hopes to work as a nurse in the future.", exja: "彼女は将来看護師として働きたいと思っている。" },
  { no:  250, en: "middle", ja: "真ん中／中央", kana: "まんなか", ex: "A huge tree stands in the middle of the field.", exja: "巨大な木が野原の真ん中に立っている。" },
  { no:  252, en: "beside", ja: "〜のそばに", kana: "そばに", ex: "A little brown dog sat beside my chair.", exja: "小さな茶色の犬が私の椅子のそばに座った。" },
  { no:  253, en: "distance", ja: "距離", kana: "きょり", ex: "The distance between the two towns is ten kilometers.", exja: "その二つの町の距離は十キロだ。" },
  { no:  253, en: "distant", ja: "遠い／離れた", kana: "とおい", ex: "We heard a distant bell through the thick fog.", exja: "濃い霧の中から遠い鐘の音が聞こえた。" },
  { no:  255, en: "favor", ja: "好意／親切な行い", kana: "こうい", ex: "Can I ask you a small favor this afternoon?", exja: "今日の午後、少しお願いしてもいいですか。" },
  { no:  255, en: "favorable", ja: "好意的な／有利な", kana: "ゆうりな", ex: "The wind was favorable for the little sailing boat.", exja: "風は小さなヨットにとって有利だった。" },
  { no:  260, en: "review", ja: "〜を復習する／批評", kana: "ふくしゅうする", ex: "I review my notes every night before bed.", exja: "私は毎晩寝る前にノートを復習する。" },
  { no:  260, en: "revise", ja: "〜を修正する／見直す", kana: "しゅうせいする", ex: "She revised her essay after hearing her teacher's advice.", exja: "彼女は先生の助言を聞いて作文を修正した。" },
  { no:  268, en: "grant", ja: "〜を与える／認める", kana: "あたえる", ex: "The king granted land to the young soldier.", exja: "王は若い兵士に土地を与えた。" },
  { no:  269, en: "pride", ja: "誇り／自尊心", kana: "ほこり", ex: "He spoke about his hometown with real pride.", exja: "彼は心からの誇りを持って故郷について語った。" },
  { no:  269, en: "proud", ja: "誇りに思って", kana: "ほこらしい", ex: "My parents were proud of my speech.", exja: "両親は私のスピーチを誇りに思ってくれた。" },
  { no:  270, en: "absence", ja: "欠席／不在", kana: "けっせき", ex: "Her absence from practice surprised the whole team.", exja: "彼女の練習の欠席はチーム全員を驚かせた。" },
  { no:  270, en: "absent", ja: "欠席の／不在の", kana: "ふざいの", ex: "Three students were absent because of the flu.", exja: "三人の生徒がインフルエンザで欠席した。" },
  { no:  273, en: "famous", ja: "有名な", kana: "ゆうめいな", ex: "This small town is famous for its old castle.", exja: "この小さな町は古い城で有名だ。" },
  { no:  276, en: "exchange", ja: "〜を交換する／交換", kana: "こうかんする", ex: "We exchanged phone numbers at the school festival.", exja: "私たちは学園祭で電話番号を交換した。" },
  { no:  278, en: "invitation", ja: "招待／招待状", kana: "しょうたい", ex: "I received an invitation to my cousin's wedding.", exja: "いとこの結婚式の招待状が届いた。" },
  { no:  278, en: "invite", ja: "〜を招待する", kana: "まねく", ex: "They invited us to dinner next Saturday.", exja: "彼らは次の土曜の夕食に私たちを招いてくれた。" },
  { no:  279, en: "add", ja: "〜を加える", kana: "くわえる", ex: "Add a little salt to the soup at the end.", exja: "最後にスープに少し塩を加えなさい。" },
  { no:  279, en: "addition", ja: "追加／足し算", kana: "ついか", ex: "The addition of one room made the house much better.", exja: "一部屋の追加で家はずっと良くなった。" },
  { no:  279, en: "additional", ja: "追加の／さらなる", kana: "さらなる", ex: "We need additional chairs for tonight's guests.", exja: "今夜の客のために追加の椅子が必要だ。" },
  { no:  280, en: "prefer", ja: "〜をより好む", kana: "このむ", ex: "I prefer green tea to coffee in the morning.", exja: "私は朝はコーヒーより緑茶を好む。" },
  { no:  287, en: "postpone", ja: "〜を延期する", kana: "えんきする", ex: "They postponed the match because of heavy rain.", exja: "大雨のため彼らは試合を延期した。" },
  { no:  288, en: "extinguish", ja: "〜を消す／消火する", kana: "しょうかする", ex: "Firefighters extinguished the fire in less than an hour.", exja: "消防士たちは一時間もかからずに火を消した。" },
  { no:  292, en: "participant", ja: "参加者", kana: "さんかしゃ", ex: "Every participant received a small towel as a gift.", exja: "参加者は全員おみやげに小さなタオルをもらった。" },
  { no:  292, en: "participate", ja: "参加する", kana: "さんかする", ex: "Many students participated in the river cleaning event.", exja: "多くの生徒が川の清掃行事に参加した。" },
  { no:  292, en: "participation", ja: "参加", kana: "さんか", ex: "Your participation in tomorrow's meeting is welcome.", exja: "明日の会議へのあなたの参加を歓迎します。" },
  { no:  293, en: "perform", ja: "〜を行う／演じる", kana: "おこなう", ex: "The band performed three new songs that night.", exja: "そのバンドはその夜、新曲を三つ演奏した。" },
  { no:  293, en: "performance", ja: "演技／出来栄え", kana: "えんぎ", ex: "Her performance on the stage moved the whole audience.", exja: "舞台での彼女の演技は観客全員を感動させた。" },
  { no:  294, en: "task", ja: "仕事／課題", kana: "しごと", ex: "My first task was to clean the windows.", exja: "私の最初の仕事は窓を掃除することだった。" },
  { no:  295, en: "negative", ja: "否定的な／悪い", kana: "ひていてきな", ex: "He gave a negative answer to my simple question.", exja: "彼は私の簡単な質問に否定的な答えをした。" },
  { no:  295, en: "positive", ja: "肯定的な／前向きな", kana: "まえむきな", ex: "Try to keep a positive mind before the test.", exja: "試験の前は前向きな気持ちを保つようにしよう。" },
  { no:  296, en: "attitude", ja: "態度／考え方", kana: "たいど", ex: "His attitude toward homework changed this year.", exja: "宿題に対する彼の態度は今年変わった。" },
  { no:  296, en: "posture", ja: "姿勢", kana: "しせい", ex: "Good posture helps you study for a long time.", exja: "良い姿勢は長時間の勉強を助ける。" },
  { no:  298, en: "image", ja: "印象／画像", kana: "いんしょう", ex: "The image on the old screen was too dark.", exja: "古い画面の映像は暗すぎた。" },
  { no:  298, en: "imagination", ja: "想像力", kana: "そうぞうりょく", ex: "Young children often have a rich imagination.", exja: "幼い子どもはしばしば豊かな想像力を持つ。" },
  { no:  298, en: "imagine", ja: "〜を想像する", kana: "そうぞうする", ex: "Imagine a city without any cars at all.", exja: "車が一台もない街を想像してごらん。" },
  { no:  299, en: "judge", ja: "〜を判断する／裁判官", kana: "はんだんする", ex: "Don't judge a person by their clothes.", exja: "服装で人を判断してはいけない。" },
  { no:  299, en: "judgment", ja: "判断／判決", kana: "はんだん", ex: "I trust your judgment in this difficult case.", exja: "この難しい件ではあなたの判断を信じます。" },
  { no:  300, en: "appear", ja: "現れる／〜のように見える", kana: "あらわれる", ex: "A bright rainbow appeared after the evening rain.", exja: "夕方の雨の後に鮮やかな虹が現れた。" },
  { no:  300, en: "appearance", ja: "外見／出現", kana: "がいけん", ex: "His appearance changed a lot during the long trip.", exja: "長い旅の間に彼の外見はずいぶん変わった。" },
];


// ---------------------------------------------------------------
// 収録範囲（メニューの初期表示に使う）
function getJukenMeta() {
  const nos = JUKEN_WORDS.map(w => w.no);
  return {
    total: JUKEN_WORDS.length,
    minNo: Math.min.apply(null, nos),
    maxNo: Math.max.apply(null, nos)
  };
}

// ---------------------------------------------------------------
// 出題データ取得
//   opts.from / opts.to : 見出し語番号の範囲（省略すると全範囲）
//   opts.limit          : 1回の出題数
//   opts.shuffle        : true ならシャッフル、false なら番号の若い順
function getJukenWords(opts) {
  opts = opts || {};
  const from  = Number(opts.from)  || 0;
  const to    = Number(opts.to)    || 0;
  const limit = Number(opts.limit) || 20;

  let words = JUKEN_WORDS.filter(w =>
    (!from || w.no >= from) && (!to || w.no <= to)
  );

  const matched = words.length;

  if (opts.shuffle) {
    for (let i = words.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [words[i], words[j]] = [words[j], words[i]];
    }
  } else {
    words.sort((a, b) => a.no - b.no);
  }

  return { words: words.slice(0, limit), matched: matched };
}
