// ===============================================================
// JukenWords.gs
// 大学受験モード（英単語）のデータ
//
//   no   : 単語帳の見出し語番号（出題順・範囲指定のキー）
//   en   : 英単語（第1問の答え。英字でタイプさせる）
//   ja   : 日本語の意味（第1問の問題文として表示）
//   kana : 第2問の答え（ひらがな。ローマ字入力でタイプさせる）
//   ex   : 例文（第2問で音声読み上げ＋文脈として表示）
//   exja : 例文の和訳。【】で囲んだ箇所が第2問の空欄になる
//
// 見出し語と番号は利用者が所有する単語帳の並びに対応させているが、
// 訳文・例文・和訳はすべて本アプリ用の書き下ろし。発音は端末側の
// 音声合成（Web Speech API）で生成するため音声ファイルは持たない。
// ===============================================================

const JUKEN_WORDS = [
  { no:    1, en: "diet", ja: "食事／食生活", kana: "しょくじ", ex: "A balanced diet keeps your body strong.", exja: "バランスの取れた【食事】は体を丈夫に保つ。" },
  { no:    1, en: "dietary", ja: "食事の／飲食物の", kana: "しょくじの", ex: "The doctor gave my father dietary advice.", exja: "医者は父に【食事の】助言をした。" },
  { no:    2, en: "ingredient", ja: "材料／成分", kana: "ざいりょう", ex: "Please mix all the ingredients in a large bowl.", exja: "大きなボウルで【材料】をすべて混ぜてください。" },
  { no:    3, en: "preparation", ja: "準備／下ごしらえ", kana: "じゅんび", ex: "Preparation for the school festival took two weeks.", exja: "学園祭の【準備】には二週間かかった。" },
  { no:    3, en: "prepare", ja: "〜を用意する／準備する", kana: "よういする", ex: "She prepared a simple lunch for her brother.", exja: "彼女は弟のために簡単な昼食を【用意した】。" },
  { no:    4, en: "boil", ja: "〜を沸かす／ゆでる", kana: "わかす", ex: "Boil the water before you add the noodles.", exja: "麺を入れる前にお湯を【沸かし】なさい。" },
  { no:    5, en: "bake", ja: "〜を（オーブンで）焼く", kana: "やく", ex: "My sister baked a chocolate cake yesterday.", exja: "姉は昨日チョコレートケーキを【焼いた】。" },
  { no:    5, en: "broil", ja: "〜を直火で焼く", kana: "じかびでやく", ex: "The cook broiled the fish over a hot fire.", exja: "料理人は魚を【直火で焼いた】。" },
  { no:    5, en: "roast", ja: "〜をあぶり焼きにする", kana: "あぶりやき", ex: "They roasted a whole chicken for the party.", exja: "彼らはパーティーのために鶏を丸ごと【あぶり焼き】にした。" },
  { no:    6, en: "fry", ja: "〜を油でいためる／揚げる", kana: "いためる", ex: "He fried some onions in a small pan.", exja: "彼は小さな鍋で玉ねぎを【いためた】。" },
  { no:    7, en: "taste", ja: "味／〜の味がする", kana: "あじ", ex: "This soup has a slightly sweet taste.", exja: "このスープは少し甘い【味】がする。" },
  { no:    7, en: "tasty", ja: "おいしい", kana: "おいしい", ex: "The bread from that little shop is very tasty.", exja: "あの小さな店のパンはとても【おいしい】。" },
  { no:    8, en: "smell", ja: "におい／〜のにおいがする", kana: "におい", ex: "The kitchen smelled of fresh coffee.", exja: "台所はいれたてのコーヒーの【におい】がした。" },
  { no:    9, en: "bite", ja: "〜にかみつく／かむ", kana: "かみつく", ex: "The little dog bit my finger.", exja: "その小さな犬は私の指に【かみついた】。" },
  { no:    9, en: "chew", ja: "〜をよくかむ", kana: "よくかむ", ex: "You should chew your food slowly.", exja: "食べ物はゆっくり【よくかむ】べきだ。" },
  { no:   10, en: "swallow", ja: "〜を飲み込む", kana: "のみこむ", ex: "He swallowed the medicine with a glass of water.", exja: "彼はコップ一杯の水で薬を【飲み込んだ】。" },

  { no:   11, en: "serve", ja: "（食事）を出す／〜に仕える", kana: "ていきょうする", ex: "That restaurant serves breakfast until eleven.", exja: "あのレストランは十一時まで朝食を【提供する】。" },
  { no:   11, en: "service", ja: "接客／奉仕／公共事業", kana: "せっきゃく", ex: "The service at the old hotel was excellent.", exja: "その古いホテルの【接客】はすばらしかった。" },
  { no:   12, en: "feed", ja: "〜に食べ物を与える", kana: "えさをやる", ex: "She feeds her cat twice a day.", exja: "彼女は猫に一日二回【えさをやる】。" },
  { no:   12, en: "food", ja: "食べ物", kana: "たべもの", ex: "We bought food for the camping trip.", exja: "私たちはキャンプ旅行のための【食べ物】を買った。" },
  { no:   13, en: "cash", ja: "現金", kana: "げんきん", ex: "I paid for the concert tickets in cash.", exja: "私はコンサートの券の代金を【現金】で払った。" },
  { no:   14, en: "discount", ja: "割引", kana: "わりびき", ex: "The store offered a big discount on winter coats.", exja: "その店は冬のコートに大きな【割引】をつけた。" },
  { no:   15, en: "bargain", ja: "買い得品／取引する", kana: "かいどく", ex: "This jacket was a real bargain.", exja: "この上着は本当に【買い得】だった。" },
  { no:   16, en: "reason", ja: "理由／理性", kana: "りゆう", ex: "Tell me the reason you were late this morning.", exja: "今朝遅れた【理由】を教えてください。" },
  { no:   16, en: "reasonable", ja: "（値段が）手ごろな／妥当な", kana: "てごろな", ex: "The price of this bike is quite reasonable.", exja: "この自転車はかなり【手ごろな】値段だ。" },
  { no:   17, en: "spend", ja: "（お金・時間）を使う", kana: "つかう", ex: "I spent three hours on my science homework.", exja: "私は理科の宿題に三時間【使った】。" },
  { no:   18, en: "sweep", ja: "〜を（ほうきで）掃く", kana: "ほうきではく", ex: "He swept the floor after dinner.", exja: "彼は夕食のあとに床を【ほうきで掃いた】。" },
  { no:   18, en: "vacuum", ja: "掃除機／〜に掃除機をかける", kana: "そうじき", ex: "She vacuumed the living room this morning.", exja: "彼女は今朝、居間に【掃除機】をかけた。" },
  { no:   19, en: "wipe", ja: "〜をふき取る／ぬぐう", kana: "ふきとる", ex: "Wipe the table with this wet cloth.", exja: "このぬれた布でテーブルを【ふき取り】なさい。" },
  { no:   20, en: "cloth", ja: "布／きれ", kana: "ぬの", ex: "She covered the box with a blue cloth.", exja: "彼女は箱を青い【布】でおおった。" },
  { no:   20, en: "clothes", ja: "衣服", kana: "いふく", ex: "Put your dirty clothes in the basket.", exja: "汚れた【衣服】はかごに入れなさい。" },
  { no:   20, en: "clothing", ja: "衣類（全体）", kana: "いるい", ex: "That shop sells clothing for small children.", exja: "あの店は小さな子ども用の【衣類】を売っている。" },

  { no:   21, en: "hang", ja: "〜をつるす／かける", kana: "つるす", ex: "Hang your coat on the hook by the door.", exja: "上着をドアのそばのフックに【つるし】なさい。" },
  { no:   22, en: "housework", ja: "家事／家の仕事", kana: "いえのしごと", ex: "My brother helps with the housework on weekends.", exja: "兄は週末に【家の仕事】を手伝う。" },
  { no:   23, en: "laundry", ja: "洗濯／洗濯物", kana: "せんたく", ex: "I do the laundry every Sunday morning.", exja: "私は毎週日曜の朝に【洗濯】をする。" },
  { no:   24, en: "celebrate", ja: "〜を祝う", kana: "いわう", ex: "We celebrated my mother's birthday at home.", exja: "私たちは家で母の誕生日を【祝った】。" },
  { no:   24, en: "celebration", ja: "祝賀／お祝いの行事", kana: "しゅくが", ex: "The village held a celebration after the harvest.", exja: "村は収穫のあとに【祝賀】の行事を開いた。" },
  { no:   24, en: "celebrity", ja: "有名人", kana: "ゆうめいじん", ex: "A celebrity from Tokyo visited our small town.", exja: "東京の【有名人】が私たちの小さな町を訪れた。" },
  { no:   25, en: "ceremony", ja: "式／儀式", kana: "しきてん", ex: "The opening ceremony began at ten o'clock.", exja: "開会の【式典】は十時に始まった。" },
  { no:   26, en: "marriage", ja: "結婚", kana: "けっこん", ex: "Their marriage has lasted for twenty years.", exja: "彼らの【結婚】は二十年続いている。" },
  { no:   26, en: "marry", ja: "〜と結婚する", kana: "けっこんする", ex: "She married a teacher from her hometown.", exja: "彼女は故郷の先生と【結婚した】。" },
  { no:   27, en: "anniversary", ja: "記念日", kana: "きねんび", ex: "Our school's anniversary falls in May.", exja: "私たちの学校の【記念日】は五月にある。" },
  { no:   28, en: "funeral", ja: "葬式", kana: "そうしき", ex: "Many people came to his grandfather's funeral.", exja: "多くの人が彼の祖父の【葬式】に来た。" },
  { no:   29, en: "floor", ja: "床／（建物の）階", kana: "ゆか", ex: "The wooden floor felt cold under my feet.", exja: "木の【床】は足の下で冷たく感じた。" },
  { no:   29, en: "story", ja: "物語／（建物の）階", kana: "ものがたり", ex: "My grandmother told us a story every night.", exja: "祖母は毎晩私たちに【物語】を話してくれた。" },
  { no:   30, en: "brick", ja: "れんが", kana: "れんが", ex: "The garden wall was built with red bricks.", exja: "庭の壁は赤い【れんが】で作られていた。" },

  { no:   31, en: "ceiling", ja: "天井", kana: "てんじょう", ex: "A large lamp hangs from the ceiling.", exja: "大きなランプが【天井】からつるされている。" },
  { no:   32, en: "backyard", ja: "裏庭", kana: "うらにわ", ex: "The children played catch in the backyard.", exja: "子どもたちは【裏庭】でキャッチボールをした。" },
  { no:   32, en: "garden", ja: "庭／庭園", kana: "ていえん", ex: "My grandmother grows roses in her garden.", exja: "祖母は【庭園】でバラを育てている。" },
  { no:   32, en: "yard", ja: "庭／敷地", kana: "しきち", ex: "They parked the old truck in the yard.", exja: "彼らは古いトラックを【敷地】に止めた。" },
  { no:   33, en: "staircase", ja: "階段（全体）", kana: "かいだんぜんたい", ex: "The old staircase creaked under our feet.", exja: "古い【階段全体】が私たちの足の下できしんだ。" },
  { no:   33, en: "stairs", ja: "階段", kana: "かいだん", ex: "She ran up the stairs to her room.", exja: "彼女は自分の部屋へ【階段】を駆け上がった。" },
  { no:   34, en: "downstairs", ja: "階下へ／下の階に", kana: "したのかい", ex: "He went downstairs to answer the phone.", exja: "彼は電話に出るために【下の階】へ行った。" },
  { no:   34, en: "upstairs", ja: "階上へ／上の階に", kana: "うえのかい", ex: "My room is upstairs, next to the bathroom.", exja: "私の部屋は【上の階】の、浴室の隣だ。" },
  { no:   35, en: "follow", ja: "〜について行く／〜に従う", kana: "ついていく", ex: "A puppy followed me all the way to school.", exja: "子犬が学校までずっと私に【ついて来た】。" },
  { no:   35, en: "obey", ja: "〜に従う／〜を守る", kana: "したがう", ex: "Every driver must obey the traffic rules.", exja: "すべての運転手は交通規則に【従わ】なければならない。" },
  { no:   36, en: "rule", ja: "規則／〜を支配する", kana: "きそく", ex: "Our club has one simple rule about practice.", exja: "私たちの部には練習について簡単な【規則】が一つある。" },
  { no:   37, en: "notice", ja: "〜に気づく／掲示", kana: "きづく", ex: "I noticed a small mistake in the report.", exja: "私は報告書の小さな誤りに【気づいた】。" },
  { no:   37, en: "noticeable", ja: "目立つ／はっきり分かる", kana: "めだつ", ex: "There was a noticeable change in his voice.", exja: "彼の声には【目立つ】変化があった。" },
  { no:   38, en: "noise", ja: "騒音／物音", kana: "そうおん", ex: "The noise from the street woke me up.", exja: "通りからの【騒音】で私は目が覚めた。" },
  { no:   38, en: "sound", ja: "音／〜に聞こえる", kana: "おと", ex: "I heard the sound of rain on the roof.", exja: "屋根に当たる雨の【音】が聞こえた。" },
  { no:   39, en: "split", ja: "〜を分ける／割る", kana: "わける", ex: "They split the pizza into six pieces.", exja: "彼らはピザを六切れに【分けた】。" },
  { no:   40, en: "bill", ja: "請求書／紙幣", kana: "せいきゅうしょ", ex: "The waiter brought us the bill after dessert.", exja: "給仕はデザートのあとに【請求書】を持ってきた。" },
  { no:   40, en: "note", ja: "覚え書き／紙幣", kana: "おぼえがき", ex: "She left a short note on the kitchen table.", exja: "彼女は台所のテーブルに短い【覚え書き】を残した。" },

  { no:   41, en: "precious", ja: "貴重な／大切な", kana: "きちょうな", ex: "Water is precious in that dry country.", exja: "その乾いた国では水は【貴重な】ものだ。" },
  { no:   42, en: "memorable", ja: "忘れられない／記憶に残る", kana: "わすれがたい", ex: "The trip to the small island was memorable.", exja: "その小さな島への旅は【忘れがたい】ものだった。" },
  { no:   42, en: "memorial", ja: "記念碑／記念の", kana: "きねんひ", ex: "They built a memorial for the lost sailors.", exja: "彼らは亡くなった船乗りのために【記念碑】を建てた。" },
  { no:   42, en: "memory", ja: "記憶／思い出", kana: "きおく", ex: "I still have a clear memory of that summer.", exja: "私は今もあの夏の【記憶】をはっきり持っている。" },
  { no:   43, en: "case", ja: "場合／事例", kana: "ばあい", ex: "In that case, we should leave early.", exja: "その【場合】、私たちは早く出発すべきだ。" },
  { no:   44, en: "event", ja: "出来事／行事", kana: "できごと", ex: "Winning the contest was a big event in her life.", exja: "その大会に勝ったことは彼女の人生の大きな【出来事】だった。" },
  { no:   45, en: "accident", ja: "事故", kana: "じこ", ex: "A traffic accident closed the main road.", exja: "交通【事故】で幹線道路が通れなくなった。" },
  { no:   45, en: "accidental", ja: "偶然の／思いがけない", kana: "ぐうぜんの", ex: "Their meeting at the station was completely accidental.", exja: "駅で彼らが出会ったのは全くの【偶然の】出来事だった。" },
  { no:   46, en: "nephew", ja: "おい", kana: "おい", ex: "My nephew is only four years old.", exja: "私の【おい】はまだ四歳だ。" },
  { no:   46, en: "niece", ja: "めい", kana: "めい", ex: "Her niece won first prize in the drawing contest.", exja: "彼女の【めい】は絵のコンテストで一等賞を取った。" },
  { no:   47, en: "cousin", ja: "いとこ", kana: "いとこ", ex: "My cousin lives in a small fishing town.", exja: "私の【いとこ】は小さな漁師町に住んでいる。" },
  { no:   48, en: "relative", ja: "親戚／相対的な", kana: "しんせき", ex: "Many relatives came to our house at New Year.", exja: "正月には多くの【親戚】が家に来た。" },
  { no:   49, en: "neighbor", ja: "隣人／近所の人", kana: "りんじん", ex: "Our neighbor lent us a ladder yesterday.", exja: "昨日、【隣人】がはしごを貸してくれた。" },
  { no:   49, en: "neighborhood", ja: "近所／地域", kana: "きんじょ", ex: "There is a nice park in our neighborhood.", exja: "私たちの【近所】には良い公園がある。" },
  { no:   50, en: "citizen", ja: "市民／国民", kana: "しみん", ex: "Every citizen has the right to vote.", exja: "すべての【市民】は投票する権利を持つ。" },
  { no:   50, en: "citizenship", ja: "市民権／国籍", kana: "こくせき", ex: "He got Japanese citizenship last year.", exja: "彼は昨年、日本の【国籍】を得た。" },

  { no:   51, en: "strange", ja: "奇妙な／見知らぬ", kana: "きみょうな", ex: "I heard a strange noise under the floor.", exja: "床の下で【奇妙な】物音が聞こえた。" },
  { no:   51, en: "stranger", ja: "見知らぬ人", kana: "みしらぬひと", ex: "A stranger asked me for directions to the museum.", exja: "【見知らぬ人】が私に博物館への道をたずねた。" },
  { no:   52, en: "accept", ja: "〜を受け入れる", kana: "うけいれる", ex: "She accepted his apology with a smile.", exja: "彼女は笑顔で彼の謝罪を【受け入れた】。" },
  { no:   52, en: "acceptable", ja: "許容できる／申し分のない", kana: "きょようできる", ex: "His answer was acceptable to the teacher.", exja: "彼の答えは先生にとって【許容できる】ものだった。" },
  { no:   52, en: "acceptance", ja: "承諾／受け入れ", kana: "しょうだく", ex: "Her acceptance of the offer surprised us all.", exja: "彼女がその申し出を【承諾】したことは私たち全員を驚かせた。" },
  { no:   53, en: "refuse", ja: "〜を断る／拒む", kana: "ことわる", ex: "He refused the invitation politely.", exja: "彼はその招待を丁寧に【断った】。" },
  { no:   53, en: "reject", ja: "〜を退ける／不採用にする", kana: "しりぞける", ex: "The company rejected my first design.", exja: "その会社は私の最初の案を【退けた】。" },
  { no:   53, en: "rejection", ja: "拒絶／不採用", kana: "きょぜつ", ex: "The rejection of his plan made him angry.", exja: "計画の【拒絶】は彼を怒らせた。" },
  { no:   54, en: "lift", ja: "〜を持ち上げる", kana: "もちあげる", ex: "Can you lift this heavy box for me?", exja: "この重い箱を【持ち上げて】くれますか。" },
  { no:   55, en: "drop", ja: "〜を落とす／落ちる", kana: "おとす", ex: "I dropped my pen under the desk.", exja: "私は机の下にペンを【落とした】。" },
  { no:   56, en: "pass", ja: "〜を通り過ぎる／合格する", kana: "とおりすぎる", ex: "We passed a small church on the way home.", exja: "帰り道で小さな教会を【通り過ぎた】。" },
  { no:   57, en: "fail", ja: "失敗する／〜しそこなう", kana: "しっぱいする", ex: "They failed in their first attempt.", exja: "彼らは最初の試みで【失敗した】。" },
  { no:   57, en: "failure", ja: "失敗／うまくいかないこと", kana: "しくじり", ex: "His failure taught him an important lesson.", exja: "彼の【しくじり】は彼に大切な教訓を教えた。" },
  { no:   58, en: "severe", ja: "厳しい／深刻な", kana: "しんこくな", ex: "The town suffered severe damage from the storm.", exja: "その町は嵐で【深刻な】被害を受けた。" },
  { no:   59, en: "strict", ja: "（規則や人が）厳しい", kana: "きびしい", ex: "Our coach is strict about being on time.", exja: "私たちのコーチは時間を守ることに【厳しい】。" },
  { no:   59, en: "strictly", ja: "厳しく／厳密に", kana: "げんみつに", ex: "Smoking is strictly forbidden in this building.", exja: "この建物では喫煙は【厳密に】禁じられている。" },
  { no:   60, en: "correct", ja: "正しい／〜を訂正する", kana: "ただしい", ex: "Only one of the four answers is correct.", exja: "四つの答えのうち【正しい】のは一つだけだ。" },
  { no:   60, en: "incorrect", ja: "誤った／正しくない", kana: "あやまった", ex: "The date on the poster was incorrect.", exja: "ポスターの日付は【誤った】ものだった。" },

  { no:   61, en: "accuracy", ja: "正確さ", kana: "せいかくさ", ex: "The accuracy of his report impressed the class.", exja: "彼の報告の【正確さ】はクラスを感心させた。" },
  { no:   61, en: "accurate", ja: "正確な", kana: "せいかくな", ex: "We need an accurate map of this area.", exja: "この地域の【正確な】地図が必要だ。" },
  { no:   61, en: "inaccurate", ja: "不正確な", kana: "ふせいかくな", ex: "The old clock in the hall is a little inaccurate.", exja: "広間の古い時計は少し【不正確な】時刻を示す。" },
  { no:   62, en: "awe", ja: "畏敬の念／驚嘆", kana: "いけい", ex: "The huge waterfall filled us with awe.", exja: "その巨大な滝は私たちを【畏敬】の念で満たした。" },
  { no:   62, en: "awful", ja: "ひどい／実にいやな", kana: "ひどい", ex: "The weather was awful during our whole trip.", exja: "旅行の間ずっと天気は【ひどかった】。" },
  { no:   63, en: "terrible", ja: "恐ろしい／ひどい", kana: "おそろしい", ex: "The storm caused terrible damage to the village.", exja: "嵐は村に【恐ろしい】被害をもたらした。" },
  { no:   63, en: "terror", ja: "恐怖", kana: "きょうふ", ex: "The children screamed in terror.", exja: "子どもたちは【恐怖】で叫んだ。" },
  { no:   64, en: "horrible", ja: "ぞっとする／実にひどい", kana: "ぞっとする", ex: "He told us a horrible story about the dark cave.", exja: "彼は暗い洞窟について【ぞっとする】話をした。" },
  { no:   64, en: "horror", ja: "おののき／強い恐怖", kana: "おののき", ex: "She watched the burning house in horror.", exja: "彼女は【おののき】ながら燃える家を見ていた。" },
  { no:   65, en: "live", ja: "住む／生きる", kana: "すむ", ex: "They live near the wide river.", exja: "彼らは広い川の近くに【住んで】いる。" },
  { no:   65, en: "lively", ja: "活気のある／元気な", kana: "かっきのある", ex: "The morning market was very lively.", exja: "朝の市場はとても【活気のある】場所だった。" },
  { no:   66, en: "alive", ja: "生きている", kana: "いきている", ex: "The old cherry tree is still alive.", exja: "その古い桜の木はまだ【生きている】。" },
  { no:   67, en: "loud", ja: "大声の／音が大きい", kana: "おおごえの", ex: "His loud voice filled the small room.", exja: "彼の【大声の】話し声が小さな部屋を満たした。" },
  { no:   68, en: "aloud", ja: "声に出して", kana: "こえにだして", ex: "Please read this poem aloud.", exja: "この詩を【声に出して】読んでください。" },
  { no:   68, en: "silently", ja: "黙って／静かに", kana: "だまって", ex: "He silently left the room and closed the door.", exja: "彼は【黙って】部屋を出て、ドアを閉めた。" },
  { no:   69, en: "impossible", ja: "不可能な", kana: "ふかのうな", ex: "It is impossible to finish this in one day.", exja: "これを一日で終えるのは【不可能な】ことだ。" },
  { no:   69, en: "possibility", ja: "可能性", kana: "かのうせい", ex: "There is a possibility of snow tonight.", exja: "今夜は雪の【可能性】がある。" },
  { no:   69, en: "possible", ja: "可能な／ありうる", kana: "かのうな", ex: "Come as early as possible tomorrow.", exja: "明日は【可能な】かぎり早く来てください。" },
  { no:   70, en: "necessarily", ja: "必ずしも（〜ない）", kana: "かならずしも", ex: "A long book is not necessarily a good one.", exja: "長い本が【必ずしも】良い本とは限らない。" },
  { no:   70, en: "necessary", ja: "必要な", kana: "ひつような", ex: "Warm clothes are necessary in the mountains.", exja: "山では暖かい服が【必要な】ものだ。" },
  { no:   70, en: "necessity", ja: "必要性／必需品", kana: "ひつようせい", ex: "Water is a necessity for every living thing.", exja: "水はすべての生き物にとって【必要性】が高い。" },
  { no:   70, en: "unnecessary", ja: "不必要な", kana: "ふひつような", ex: "He bought many unnecessary things at the sale.", exja: "彼は安売りで【不必要な】物をたくさん買った。" },

  { no:   71, en: "danger", ja: "危険", kana: "きけん", ex: "The sign warns drivers of danger ahead.", exja: "その標識は運転手に前方の【危険】を知らせている。" },
  { no:   71, en: "dangerous", ja: "危険な", kana: "きけんな", ex: "Swimming in that river is dangerous.", exja: "あの川で泳ぐのは【危険な】ことだ。" },
  { no:   71, en: "safe", ja: "安全な／金庫", kana: "あんぜんな", ex: "This quiet street is safe for children.", exja: "この静かな通りは子どもにとって【安全な】場所だ。" },
  { no:   72, en: "convenience", ja: "便利さ／好都合", kana: "べんりさ", ex: "The convenience of the new station pleased everyone.", exja: "新しい駅の【便利さ】はみんなを喜ばせた。" },
  { no:   72, en: "convenient", ja: "便利な／都合のよい", kana: "べんりな", ex: "A small umbrella is convenient on rainy days.", exja: "小さな傘は雨の日に【便利な】道具だ。" },
  { no:   72, en: "inconvenient", ja: "不便な／都合の悪い", kana: "ふべんな", ex: "The bus times are inconvenient for students.", exja: "バスの時刻は学生には【不便な】ものだ。" },
  { no:   73, en: "unusual", ja: "珍しい／異常な", kana: "めずらしい", ex: "Snow in April is unusual in this town.", exja: "この町で四月に雪が降るのは【珍しい】。" },
  { no:   73, en: "usual", ja: "いつもの／普通の", kana: "いつもの", ex: "He sat in his usual seat by the window.", exja: "彼は窓際の【いつもの】席に座った。" },
  { no:   74, en: "fun", ja: "楽しみ／楽しいこと", kana: "たのしみ", ex: "We had a lot of fun at the beach.", exja: "浜辺での遊びは私たちにとって大きな【楽しみ】だった。" },
  { no:   74, en: "funny", ja: "おかしい／こっけいな", kana: "おかしい", ex: "Her funny story made everyone laugh.", exja: "彼女の話がとても【おかしい】ので、みんなは笑った。" },
  { no:   75, en: "rude", ja: "失礼な／無礼な", kana: "しつれいな", ex: "It is rude to point at people.", exja: "人を指さすのは【失礼な】ことだ。" },
  { no:   76, en: "wisdom", ja: "知恵", kana: "ちえ", ex: "We learned much from our grandmother's wisdom.", exja: "私たちは祖母の【知恵】から多くを学んだ。" },
  { no:   76, en: "wise", ja: "賢い／賢明な", kana: "かしこい", ex: "It was wise of you to bring a map.", exja: "地図を持ってきたのは【賢い】判断だった。" },
  { no:   77, en: "clear", ja: "澄んだ／明らかな", kana: "すんだ", ex: "The sky was clear after the evening rain.", exja: "夕方の雨のあと、空は【澄んだ】青色になった。" },
  { no:   77, en: "obvious", ja: "明らかな／見え見えの", kana: "あきらかな", ex: "It was obvious that he was very tired.", exja: "彼がとても疲れているのは【明らかな】ことだった。" },
  { no:   77, en: "obviously", ja: "明らかに", kana: "あきらかに", ex: "She was obviously happy about the news.", exja: "彼女はその知らせを【明らかに】喜んでいた。" },
  { no:   78, en: "fortunate", ja: "幸運な", kana: "こううんな", ex: "We were fortunate to find two seats.", exja: "席を二つ見つけられたのは【幸運な】ことだった。" },
  { no:   78, en: "fortunately", ja: "幸いにも", kana: "さいわいにも", ex: "Fortunately, no one was hurt in the fire.", exja: "【幸いにも】火事で誰もけがをしなかった。" },
  { no:   78, en: "lucky", ja: "運のよい", kana: "うんがよい", ex: "You are lucky to have such kind friends.", exja: "そんな親切な友達がいるとは【運がよい】。" },
  { no:   79, en: "pity", ja: "哀れみ／残念なこと", kana: "あわれみ", ex: "She felt pity for the lost kitten.", exja: "彼女は迷子の子猫に【哀れみ】を感じた。" },
  { no:   80, en: "shame", ja: "恥／残念なこと", kana: "はじ", ex: "He felt shame after telling the lie.", exja: "うそをついたあと、彼は【恥】を感じた。" },

  { no:   81, en: "impolite", ja: "無作法な／失礼な", kana: "ぶさほうな", ex: "It is impolite to talk with your mouth full.", exja: "口に物を入れたまま話すのは【無作法な】ことだ。" },
  { no:   81, en: "polite", ja: "礼儀正しい", kana: "れいぎただしい", ex: "The boy gave a polite answer to the guest.", exja: "その少年は客に【礼儀正しい】返事をした。" },
  { no:   82, en: "smart", ja: "頭のよい／賢い", kana: "あたまがよい", ex: "My smart little sister solved the puzzle quickly.", exja: "妹は【頭がよい】ので、すぐにパズルを解いた。" },
  { no:   83, en: "selfish", ja: "自分勝手な／利己的な", kana: "じぶんかって", ex: "His selfish behavior upset the whole team.", exja: "彼の【自分勝手】な行動はチーム全体を困らせた。" },
  { no:   83, en: "selfishness", ja: "利己心／身勝手さ", kana: "りこしん", ex: "Her selfishness cost her many friends.", exja: "彼女の【利己心】は多くの友人を失わせた。" },
  { no:   84, en: "lazy", ja: "なまけた／怠惰な", kana: "なまけた", ex: "The lazy cat slept all afternoon.", exja: "その【なまけた】猫は午後じゅう眠っていた。" },
  { no:   85, en: "gentle", ja: "優しい／穏やかな", kana: "やさしい", ex: "The nurse spoke in a gentle voice.", exja: "その看護師は【優しい】声で話した。" },
  { no:   86, en: "calm", ja: "落ち着いた／〜を静める", kana: "おちついた", ex: "Try to stay calm during the test.", exja: "試験の間は【落ち着いた】態度でいなさい。" },
  { no:   87, en: "nerve", ja: "神経／度胸", kana: "しんけい", ex: "The cold air hurt the nerves in my teeth.", exja: "冷たい空気が歯の【神経】にしみた。" },
  { no:   87, en: "nervous", ja: "緊張した／不安な", kana: "きんちょうした", ex: "I felt nervous before my speech.", exja: "私はスピーチの前に【緊張した】。" },
  { no:   88, en: "exhausted", ja: "疲れ果てた", kana: "つかれはてた", ex: "After the long walk, we were exhausted.", exja: "長い道のりを歩いたあと、私たちは【疲れ果てた】。" },
  { no:   88, en: "weary", ja: "くたびれた／うんざりした", kana: "くたびれた", ex: "The weary travelers sat down beside the road.", exja: "【くたびれた】旅人たちは道ばたに座った。" },
  { no:   89, en: "income", ja: "収入", kana: "しゅうにゅう", ex: "His income is smaller than he hoped.", exja: "彼の【収入】は望んだよりも少ない。" },
  { no:   90, en: "salary", ja: "給料", kana: "きゅうりょう", ex: "She saves part of her salary every month.", exja: "彼女は毎月、【給料】の一部を貯金している。" },
  { no:   90, en: "wage", ja: "賃金", kana: "ちんぎん", ex: "The workers asked for higher wages.", exja: "労働者たちはより高い【賃金】を求めた。" },

  { no:   91, en: "popular", ja: "人気のある", kana: "にんきのある", ex: "That song is popular among high school students.", exja: "あの歌は高校生の間で【人気のある】曲だ。" },
  { no:   91, en: "population", ja: "人口", kana: "じんこう", ex: "The population of this town is falling slowly.", exja: "この町の【人口】は少しずつ減っている。" },
  { no:   92, en: "cost", ja: "費用／〜がかかる", kana: "ひよう", ex: "The cost of the trip was higher than we thought.", exja: "旅行の【費用】は思ったより高かった。" },
  { no:   92, en: "costly", ja: "高価な／犠牲の大きい", kana: "こうかな", ex: "Repairing the old roof was costly.", exja: "古い屋根の修理は【高価な】ものだった。" },
  { no:   93, en: "risk", ja: "危険性／恐れ", kana: "きけんせい", ex: "There is a risk of heavy rain tomorrow.", exja: "明日は大雨の【危険性】がある。" },
  { no:   93, en: "risky", ja: "あぶない／危険を伴う", kana: "あぶない", ex: "Climbing that rock alone is risky.", exja: "あの岩に一人で登るのは【あぶない】。" },
  { no:   94, en: "satisfaction", ja: "満足", kana: "まんぞく", ex: "He looked at his work with satisfaction.", exja: "彼は【満足】して自分の作品を眺めた。" },
  { no:   94, en: "satisfactory", ja: "十分な／満足のいく", kana: "じゅうぶんな", ex: "Her test results were satisfactory this time.", exja: "今回の彼女の試験の結果は【十分な】ものだった。" },
  { no:   94, en: "satisfied", ja: "満足した", kana: "まんぞくした", ex: "The customers were satisfied with the meal.", exja: "客たちはその食事に【満足した】。" },
  { no:   94, en: "satisfying", ja: "満ち足りた／満足させる", kana: "みちたりた", ex: "Finishing the project was a satisfying experience.", exja: "その企画をやり遂げたのは【満ち足りた】経験だった。" },
  { no:   95, en: "pleasant", ja: "快い／感じのよい", kana: "こころよい", ex: "We spent a pleasant afternoon in the park.", exja: "私たちは公園で【快い】午後を過ごした。" },
  { no:   95, en: "please", ja: "〜を喜ばせる", kana: "よろこばせる", ex: "The small gift pleased my little brother.", exja: "その小さな贈り物は弟を【喜ばせた】。" },
  { no:   95, en: "pleased", ja: "うれしく思う／喜んだ", kana: "うれしい", ex: "She was pleased to hear from her old friend.", exja: "昔の友人から便りがあって、彼女は【うれしい】気持ちになった。" },
  { no:   96, en: "bored", ja: "退屈した", kana: "たいくつした", ex: "The children got bored during the long speech.", exja: "子どもたちは長い話の間に【退屈した】。" },
  { no:   96, en: "boredom", ja: "退屈さ", kana: "たいくつさ", ex: "He read old magazines out of boredom.", exja: "彼は【退屈さ】から古い雑誌を読んだ。" },
  { no:   96, en: "boring", ja: "つまらない／退屈な", kana: "つまらない", ex: "The movie was long and boring.", exja: "その映画は長くて【つまらない】ものだった。" },
  { no:   97, en: "confused", ja: "混乱した／当惑した", kana: "こんらんした", ex: "I was confused by the strange map.", exja: "私はその奇妙な地図に【混乱した】。" },
  { no:   97, en: "confusing", ja: "分かりにくい／紛らわしい", kana: "わかりにくい", ex: "The instructions were confusing to everyone.", exja: "その説明は誰にとっても【分かりにくい】ものだった。" },
  { no:   97, en: "confusion", ja: "混乱", kana: "こんらん", ex: "There was confusion at the station after the accident.", exja: "事故のあと、駅は【混乱】していた。" },
  { no:   98, en: "scare", ja: "〜を怖がらせる", kana: "こわがらせる", ex: "The loud thunder scared the baby.", exja: "大きな雷は赤ん坊を【怖がらせた】。" },
  { no:   98, en: "scared", ja: "おびえた／怖がった", kana: "おびえた", ex: "The scared puppy hid under the sofa.", exja: "【おびえた】子犬はソファの下に隠れた。" },
  { no:   98, en: "scary", ja: "怖い／恐ろしい", kana: "こわい", ex: "We watched a scary movie last night.", exja: "私たちは昨夜、【怖い】映画を見た。" },
  { no:   99, en: "embarrassed", ja: "恥ずかしい／きまり悪い", kana: "はずかしい", ex: "He was embarrassed when he forgot her name.", exja: "彼女の名前を忘れて、彼は【恥ずかしい】思いをした。" },
  { no:   99, en: "embarrassing", ja: "気まずい／恥ずかしくさせる", kana: "きまずい", ex: "That was an embarrassing moment for all of us.", exja: "あれは私たち全員にとって【気まずい】瞬間だった。" },
  { no:   99, en: "embarrassment", ja: "当惑／きまり悪さ", kana: "とうわく", ex: "Her face turned red with embarrassment.", exja: "彼女の顔は【当惑】で赤くなった。" },
  { no:  100, en: "disappointed", ja: "がっかりした／失望した", kana: "がっかりした", ex: "I was disappointed with the final result.", exja: "私は最終の結果に【がっかりした】。" },
  { no:  100, en: "disappointing", ja: "期待外れの", kana: "きたいはずれ", ex: "The concert was disappointing to many fans.", exja: "そのコンサートは多くのファンにとって【期待外れ】だった。" },
  { no:  100, en: "disappointment", ja: "失望／落胆", kana: "しつぼう", ex: "He could not hide his disappointment.", exja: "彼は【失望】を隠すことができなかった。" },

  { no:  101, en: "variety", ja: "多様性／さまざまな種類", kana: "たようせい", ex: "The shop sells a wide variety of fresh fruits.", exja: "その店は実に【多様性】に富んだ新鮮な果物を売っている。" },
  { no:  101, en: "various", ja: "さまざまな／いろいろな", kana: "さまざまな", ex: "Students come to this club for various reasons.", exja: "生徒たちは【さまざまな】理由でこのクラブに来る。" },
  { no:  102, en: "irregular", ja: "不規則な／不ぞろいな", kana: "ふきそくな", ex: "His sleeping hours have been irregular these days.", exja: "最近、彼は【不規則な】時間に寝ている。" },
  { no:  102, en: "regular", ja: "規則正しい／定期的な", kana: "きそくただしい", ex: "She takes a regular walk before breakfast.", exja: "彼女は朝食前に【規則正しい】散歩をしている。" },
  { no:  103, en: "pale", ja: "青白い／色が薄い", kana: "あおじろい", ex: "You look pale, so you should rest a little.", exja: "顔が【青白い】よ。少し休んだほうがいい。" },
  { no:  104, en: "ugly", ja: "醜い／見苦しい", kana: "みにくい", ex: "The old factory looked ugly after the fire.", exja: "その古い工場は火事のあと【醜い】姿になった。" },
  { no:  105, en: "delicate", ja: "繊細な／壊れやすい", kana: "せんさいな", ex: "She has a delicate sense of color.", exja: "彼女は色に対する【繊細な】感覚を持っている。" },
  { no:  106, en: "flexibility", ja: "柔軟性／しなやかさ", kana: "じゅうなんせい", ex: "Daily stretching improves the flexibility of your body.", exja: "毎日のストレッチは体の【柔軟性】を高める。" },
  { no:  106, en: "flexible", ja: "柔軟な／融通のきく", kana: "じゅうなんな", ex: "Our teacher is flexible about the deadline.", exja: "私たちの先生は締め切りについて【柔軟な】考え方をする。" },
  { no:  107, en: "tidy", ja: "きちんとした／整った", kana: "きちんとした", ex: "He keeps his desk tidy every day.", exja: "彼の机は毎日【きちんとした】状態に保たれている。" },
  { no:  108, en: "plain", ja: "質素な／分かりやすい", kana: "しっそな", ex: "She wore a plain white dress to the party.", exja: "彼女はパーティーに【質素な】白い服を着ていった。" },
  { no:  109, en: "rough", ja: "粗い／荒々しい", kana: "あらい", ex: "The surface of this stone feels rough.", exja: "この石の表面は【粗い】感じがする。" },
  { no:  109, en: "roughly", ja: "おおよそ／乱暴に", kana: "おおよそ", ex: "The trip takes roughly three hours by bus.", exja: "その旅はバスで【おおよそ】3時間かかる。" },
  { no:  109, en: "smooth", ja: "なめらかな／順調な", kana: "なめらかな", ex: "The baby's skin is very smooth.", exja: "赤ちゃんの肌はとても【なめらかな】手ざわりだ。" },
  { no:  110, en: "flat", ja: "平らな／平たい", kana: "たいらな", ex: "We put our tent on flat ground.", exja: "私たちは【平らな】地面にテントを張った。" },

  { no:  111, en: "empty", ja: "空の／人のいない", kana: "からっぽ", ex: "The box was empty when I opened it.", exja: "箱を開けたとき、中は【空っぽ】だった。" },
  { no:  112, en: "even", ja: "均等な／〜でさえ", kana: "きんとうな", ex: "We divided the cake into even pieces.", exja: "私たちはケーキを【均等な】大きさに分けた。" },
  { no:  112, en: "uneven", ja: "でこぼこの／不均等な", kana: "でこぼこ", ex: "The old road is uneven, so drive slowly.", exja: "その古い道は【でこぼこ】なので、ゆっくり運転して。" },
  { no:  113, en: "broad", ja: "幅の広い／範囲の広い", kana: "はばひろい", ex: "A broad river runs through this town.", exja: "【幅広い】川がこの町を流れている。" },
  { no:  113, en: "narrow", ja: "狭い／細い", kana: "せまい", ex: "We walked along a narrow path in the woods.", exja: "私たちは森の【狭い】小道を歩いた。" },
  { no:  113, en: "wide", ja: "広い／幅のある", kana: "ひろい", ex: "The garden is wide enough for a soccer game.", exja: "その庭はサッカーをするのに十分【広い】。" },
  { no:  114, en: "deep", ja: "深い／深刻な", kana: "ふかい", ex: "This lake is deeper than it looks.", exja: "この湖は見た目よりも【深い】。" },
  { no:  114, en: "shallow", ja: "浅い／浅はかな", kana: "あさい", ex: "Children can play safely in the shallow water.", exja: "子どもたちは【浅い】水の中で安全に遊べる。" },
  { no:  115, en: "dense", ja: "密集した／濃い", kana: "みっしゅうした", ex: "A dense forest covers the northern hills.", exja: "【密集した】森が北の丘を覆っている。" },
  { no:  115, en: "thick", ja: "厚い／太い", kana: "あつい", ex: "He read a thick book during the holidays.", exja: "彼は休みの間に【厚い】本を読んだ。" },
  { no:  116, en: "thin", ja: "薄い／やせた", kana: "うすい", ex: "Cut the bread into thin slices, please.", exja: "パンを【薄い】スライスに切ってください。" },
  { no:  117, en: "huge", ja: "巨大な／ばく大な", kana: "きょだいな", ex: "A huge ship entered the harbor this morning.", exja: "【巨大な】船が今朝、港に入ってきた。" },
  { no:  118, en: "tiny", ja: "ごく小さい／わずかな", kana: "ごくちいさい", ex: "A tiny bird was sitting on the wire.", exja: "【ごく小さい】鳥が電線にとまっていた。" },
  { no:  119, en: "careful", ja: "注意深い／慎重な", kana: "ちゅういぶかい", ex: "Be careful when you cross this street.", exja: "この通りを渡るときは【注意深い】態度が必要だ。" },
  { no:  119, en: "careless", ja: "不注意な／うっかりした", kana: "ふちゅういな", ex: "His careless mistake broke the machine.", exja: "彼の【不注意な】ミスが機械を壊した。" },
  { no:  120, en: "mistake", ja: "間違い／誤り", kana: "まちがい", ex: "I made a small mistake in the calculation.", exja: "私は計算で小さな【間違い】をした。" },

  { no:  121, en: "earn", ja: "〜を稼ぐ／〜を得る", kana: "かせぐ", ex: "She earns money by teaching piano.", exja: "彼女はピアノを教えてお金を【稼いで】いる。" },
  { no:  121, en: "earnings", ja: "収入／もうけ", kana: "しゅうにゅう", ex: "He saved half of his earnings last year.", exja: "彼は昨年、【収入】の半分を貯金した。" },
  { no:  123, en: "crowd", ja: "群衆／人混み", kana: "ぐんしゅう", ex: "A large crowd waited in front of the gate.", exja: "大きな【群衆】が門の前で待っていた。" },
  { no:  124, en: "gather", ja: "〜を集める／集まる", kana: "あつめる", ex: "The students gathered in the gym at noon.", exja: "正午に生徒たちを体育館に【集めた】。" },
  { no:  125, en: "ability", ja: "能力／才能", kana: "のうりょく", ex: "She has the ability to solve hard problems.", exja: "彼女は難しい問題を解く【能力】がある。" },
  { no:  125, en: "able", ja: "〜することができる", kana: "できる", ex: "I was able to finish the report last night.", exja: "私は昨夜、その報告書を終えることが【できた】。" },
  { no:  125, en: "disability", ja: "障害／不自由", kana: "しょうがい", ex: "This museum is designed for people with a disability.", exja: "この博物館は【障害】のある人のために設計されている。" },
  { no:  126, en: "courage", ja: "勇気／度胸", kana: "ゆうき", ex: "It took courage to speak in front of everyone.", exja: "みんなの前で話すには【勇気】が必要だった。" },
  { no:  127, en: "duty", ja: "義務／務め", kana: "ぎむ", ex: "It is our duty to protect this river.", exja: "この川を守ることは私たちの【義務】だ。" },
  { no:  128, en: "attempt", ja: "試み／〜を試みる", kana: "こころみる", ex: "He made a second attempt to climb the wall.", exja: "彼は2度目に壁を登ることを【試みた】。" },
  { no:  129, en: "tend", ja: "〜する傾向がある", kana: "けいこうがある", ex: "People tend to eat more when they are tired.", exja: "人は疲れているとより多く食べる【傾向がある】。" },
  { no:  129, en: "tendency", ja: "傾向／性質", kana: "けいこう", ex: "He has a tendency to forget people's names.", exja: "彼には人の名前を忘れる【傾向】がある。" },
  { no:  130, en: "struggle", ja: "奮闘する／もがく", kana: "もがく", ex: "She struggled to open the heavy door.", exja: "彼女は重い扉を開けようと【もがいた】。" },

  { no:  131, en: "mend", ja: "〜を繕う／〜を直す", kana: "つくろう", ex: "My grandmother mended my torn shirt.", exja: "祖母が破れたシャツを【繕って】くれた。" },
  { no:  131, en: "repair", ja: "〜を修理する", kana: "しゅうりする", ex: "They repaired the roof before the rainy season.", exja: "彼らは梅雨の前に屋根を【修理した】。" },
  { no:  132, en: "fix", ja: "〜を直す／〜を固定する", kana: "なおす", ex: "Can you fix my bicycle by Friday?", exja: "金曜日までに私の自転車を【直す】ことはできますか。" },
  { no:  133, en: "handle", ja: "〜を扱う／取っ手", kana: "あつかう", ex: "She handles difficult customers very calmly.", exja: "彼女は難しい客をとても落ち着いて【扱う】。" },
  { no:  134, en: "operate", ja: "〜を操作する／手術する", kana: "そうさする", ex: "Only trained staff may operate this machine.", exja: "訓練を受けた職員だけがこの機械を【操作する】ことができる。" },
  { no:  134, en: "operation", ja: "手術／操作／作戦", kana: "しゅじゅつ", ex: "The operation on his knee went well.", exja: "彼のひざの【手術】はうまくいった。" },
  { no:  135, en: "remain", ja: "残る／〜のままである", kana: "のこる", ex: "Only two cookies remained on the plate.", exja: "皿の上には2枚のクッキーしか【残って】いなかった。" },
  { no:  136, en: "leave", ja: "〜を去る／〜を置き忘れる", kana: "さる", ex: "We must leave the station before six.", exja: "私たちは6時前に駅を【去る】必要がある。" },
  { no:  137, en: "continue", ja: "〜を続ける／続く", kana: "つづける", ex: "The rain continued all through the night.", exja: "雨は一晩中降り【続けた】。" },
  { no:  137, en: "continuous", ja: "絶え間ない／連続した", kana: "たえまない", ex: "The continuous noise made it hard to study.", exja: "【絶え間ない】騒音のせいで勉強しにくかった。" },
  { no:  138, en: "last", ja: "続く／最後の", kana: "つづく", ex: "The concert lasted almost three hours.", exja: "そのコンサートはほぼ3時間【続いた】。" },
  { no:  139, en: "scold", ja: "〜をしかる", kana: "しかる", ex: "His father scolded him for coming home late.", exja: "彼の父は帰宅が遅いことで彼を【しかった】。" },
  { no:  140, en: "punish", ja: "〜を罰する", kana: "ばっする", ex: "The school punished the students who cheated.", exja: "学校は不正をした生徒たちを【罰した】。" },
  { no:  140, en: "punishment", ja: "罰／処罰", kana: "しょばつ", ex: "Losing his phone for a week was a fair punishment.", exja: "1週間電話を取り上げられたのは妥当な【処罰】だった。" },

  { no:  141, en: "blame", ja: "〜を責める／責任", kana: "せめる", ex: "Don't blame your brother for the broken cup.", exja: "割れたカップのことで弟を【責めて】はいけない。" },
  { no:  142, en: "fault", ja: "責任／過失／欠点", kana: "せきにん", ex: "The accident was not entirely my fault.", exja: "その事故は全部が私の【責任】というわけではなかった。" },
  { no:  143, en: "award", ja: "賞／〜を授与する", kana: "しょう", ex: "She received an award for her science project.", exja: "彼女は理科の研究で【賞】を受けた。" },
  { no:  143, en: "prize", ja: "賞品／賞金", kana: "しょうひん", ex: "He won first prize in the speech contest.", exja: "彼はスピーチ大会で一等の【賞品】をもらった。" },
  { no:  144, en: "reward", ja: "報酬／ほうび", kana: "ほうしゅう", ex: "They offered a reward for finding the lost dog.", exja: "彼らは迷子の犬を見つけた人に【報酬】を出した。" },
  { no:  145, en: "wrap", ja: "〜を包む", kana: "つつむ", ex: "She wrapped the gift in blue paper.", exja: "彼女は贈り物を青い紙で【包んだ】。" },
  { no:  146, en: "pack", ja: "〜を詰める／荷造りする", kana: "につくりする", ex: "I packed my bag the night before the trip.", exja: "私は旅行の前の晩にかばんを【荷造りした】。" },
  { no:  146, en: "unpack", ja: "荷をほどく／中身を出す", kana: "ほどく", ex: "He unpacked his suitcase as soon as he arrived.", exja: "彼は着くとすぐに旅行かばんの荷を【ほどいた】。" },
  { no:  147, en: "custom", ja: "慣習／しきたり", kana: "かんしゅう", ex: "Bowing is an old custom in this country.", exja: "おじぎはこの国の古い【慣習】だ。" },
  { no:  148, en: "habit", ja: "習慣／癖", kana: "しゅうかん", ex: "Reading before bed is a good habit.", exja: "寝る前に本を読むのは良い【習慣】だ。" },
  { no:  149, en: "match", ja: "試合／〜に合う", kana: "しあい", ex: "The tennis match was postponed because of rain.", exja: "テニスの【試合】は雨で延期された。" },
  { no:  150, en: "fit", ja: "〜にぴったり合う／適する", kana: "ぴったりあう", ex: "These shoes fit my feet perfectly.", exja: "この靴は私の足に【ぴったり合う】。" },

  { no:  151, en: "suit", ja: "〜に似合う／都合が合う", kana: "にあう", ex: "That blue jacket suits you very well.", exja: "その青い上着はあなたにとてもよく【似合う】。" },
  { no:  151, en: "suitable", ja: "ふさわしい／適した", kana: "ふさわしい", ex: "This film is not suitable for small children.", exja: "この映画は小さな子どもには【ふさわしい】ものではない。" },
  { no:  152, en: "manner", ja: "やり方／態度", kana: "やりかた", ex: "He answered in a friendly manner.", exja: "彼は親しみのある【やり方】で答えた。" },
  { no:  152, en: "manners", ja: "礼儀作法／行儀", kana: "れいぎさほう", ex: "Good table manners matter at a formal dinner.", exja: "正式な夕食では食事の【礼儀作法】が大切だ。" },
  { no:  153, en: "arm", ja: "腕", kana: "うで", ex: "He broke his left arm while skiing.", exja: "彼はスキー中に左の【腕】を折った。" },
  { no:  153, en: "arms", ja: "武器／兵器", kana: "へいき", ex: "The country agreed to reduce its arms.", exja: "その国は【兵器】を減らすことに同意した。" },
  { no:  154, en: "glass", ja: "ガラス／コップ", kana: "こっぷ", ex: "She poured milk into a tall glass.", exja: "彼女は背の高い【コップ】に牛乳を注いだ。" },
  { no:  154, en: "glasses", ja: "めがね", kana: "めがね", ex: "I cannot read the sign without my glasses.", exja: "【めがね】がないとその標識が読めない。" },
  { no:  156, en: "reach", ja: "〜に着く／手を伸ばす", kana: "とうちゃくする", ex: "We reached the top of the hill at sunset.", exja: "私たちは日没に丘の頂上に【到着した】。" },
  { no:  157, en: "discuss", ja: "〜について話し合う", kana: "はなしあう", ex: "The class discussed the problem for an hour.", exja: "クラスはその問題について1時間【話し合った】。" },
  { no:  157, en: "discussion", ja: "議論／話し合い", kana: "ぎろん", ex: "Their discussion about the trip went on late.", exja: "旅行についての彼らの【議論】は遅くまで続いた。" },
  { no:  158, en: "contact", ja: "連絡／〜と連絡を取る", kana: "れんらく", ex: "Please contact me if the train is late.", exja: "電車が遅れたら私に【連絡】してください。" },
  { no:  159, en: "approach", ja: "〜に近づく／取り組み方", kana: "ちかづく", ex: "A small boat approached the island slowly.", exja: "小さな船がゆっくりと島に【近づいた】。" },
  { no:  160, en: "resemble", ja: "〜に似ている", kana: "にている", ex: "She resembles her mother in many ways.", exja: "彼女は多くの点で母親に【似ている】。" },

  { no:  161, en: "lend", ja: "〜を貸す／〜を貸し出す", kana: "かしだす", ex: "Could you lend me your umbrella today?", exja: "今日、私に傘を【貸し出して】もらえますか。" },
  { no:  162, en: "borrow", ja: "〜を借りる", kana: "かりる", ex: "I borrowed two books from the library.", exja: "私は図書館で本を2冊【借りた】。" },
  { no:  163, en: "rent", ja: "家賃／〜を賃借りする", kana: "やちん", ex: "They rent a small house near the sea.", exja: "彼らは海の近くの小さな家に【家賃】を払っている。" },
  { no:  163, en: "rental", ja: "賃貸／貸し出し", kana: "ちんたい", ex: "The rental of the hall costs ten thousand yen.", exja: "そのホールの【賃貸】料は1万円かかる。" },
  { no:  164, en: "loan", ja: "貸付／借金", kana: "かしつけ", ex: "He took out a loan to buy a new car.", exja: "彼は新しい車を買うために【貸付】を受けた。" },
  { no:  166, en: "direct", ja: "直接の／〜を指揮する", kana: "ちょくせつの", ex: "There is a direct flight from Tokyo to Rome.", exja: "東京からローマへの【直接の】便がある。" },
  { no:  166, en: "director", ja: "監督／取締役", kana: "かんとく", ex: "The director asked the actors to try again.", exja: "【監督】は俳優たちにもう一度やるよう頼んだ。" },
  { no:  166, en: "indirect", ja: "間接的な／遠回しな", kana: "かんせつてきな", ex: "She gave an indirect answer to my question.", exja: "彼女は私の質問に【間接的な】答えをした。" },
  { no:  167, en: "impatient", ja: "我慢できない／いらだった", kana: "がまんできない", ex: "The children grew impatient while waiting for the bus.", exja: "子どもたちはバスを待つ間に【我慢できない】気持ちになった。" },
  { no:  167, en: "patience", ja: "忍耐／我慢強さ", kana: "にんたい", ex: "Learning a language takes a lot of patience.", exja: "言葉を学ぶには多くの【忍耐】が必要だ。" },
  { no:  167, en: "patient", ja: "患者／忍耐強い", kana: "かんじゃ", ex: "The doctor visited every patient in the room.", exja: "医師は部屋のすべての【患者】を訪ねた。" },
  { no:  168, en: "tear", ja: "涙／〜を引き裂く", kana: "なみだ", ex: "Tears ran down her face during the movie.", exja: "映画の間、【涙】が彼女の顔を流れ落ちた。" },
  { no:  169, en: "notable", ja: "注目すべき／著名な", kana: "ちゅうもくすべき", ex: "Her speech was the most notable part of the event.", exja: "彼女の演説はその催しで最も【注目すべき】部分だった。" },
  { no:  170, en: "shop", ja: "買い物をする／店", kana: "かいものする", ex: "We shopped for vegetables at the morning market.", exja: "私たちは朝市で野菜を求めて【買い物した】。" },
  { no:  170, en: "storage", ja: "保管／しまっておくこと", kana: "ほかん", ex: "We keep our winter clothes in storage under the bed.", exja: "私たちは冬服をベッドの下に【保管】している。" },
  { no:  170, en: "store", ja: "〜を蓄える／店", kana: "たくわえる", ex: "Squirrels store nuts for the winter.", exja: "リスは冬に備えて木の実を【蓄える】。" },

  { no:  171, en: "admission", ja: "入場／入学の許可", kana: "にゅうじょう", ex: "Admission to the garden is free on Sundays.", exja: "日曜日はその庭園への【入場】が無料だ。" },
  { no:  171, en: "admit", ja: "〜を認める／入場を許す", kana: "みとめる", ex: "He admitted that he had forgotten the promise.", exja: "彼は約束を忘れていたことを【認めた】。" },
  { no:  172, en: "fee", ja: "料金／謝礼", kana: "りょうきん", ex: "The club asks for a small fee every month.", exja: "そのクラブは毎月わずかな【料金】を求める。" },
  { no:  173, en: "tuition", ja: "授業料／指導", kana: "じゅぎょうりょう", ex: "His parents paid the tuition for the first year.", exja: "彼の両親は1年目の【授業料】を払った。" },
  { no:  174, en: "charge", ja: "〜を請求する／料金", kana: "せいきゅうする", ex: "The garage charged me too much for the work.", exja: "その修理工場は作業代を私に高く【請求した】。" },
  { no:  175, en: "fare", ja: "運賃", kana: "うんちん", ex: "The bus fare went up again this spring.", exja: "バスの【運賃】がこの春また上がった。" },
  { no:  176, en: "fine", ja: "罰金／立派な", kana: "ばっきん", ex: "He had to pay a fine for parking there.", exja: "彼はそこに駐車したため【罰金】を払わねばならなかった。" },
  { no:  177, en: "penalty", ja: "罰則／ばつ", kana: "ばっそく", ex: "There is a heavy penalty for breaking this rule.", exja: "この規則を破ると重い【罰則】がある。" },
  { no:  178, en: "weather", ja: "天気／天候", kana: "てんき", ex: "The weather changed suddenly in the afternoon.", exja: "午後、【天気】が急に変わった。" },
  { no:  178, en: "whether", ja: "〜かどうか", kana: "かどうか", ex: "I do not know whether she will come tonight.", exja: "彼女が今夜来る【かどうか】分からない。" },
  { no:  179, en: "forecast", ja: "予報／〜を予報する", kana: "よほう", ex: "The forecast says it will snow tomorrow.", exja: "【予報】では明日は雪が降るそうだ。" },
  { no:  180, en: "wind", ja: "風", kana: "かぜ", ex: "A cold wind shook the windows all night.", exja: "冷たい【風】が一晩中窓を揺らした。" },
  { no:  180, en: "windy", ja: "風の強い", kana: "かぜがつよい", ex: "It was too windy to ride a bicycle.", exja: "【風が強い】ので自転車に乗れなかった。" },

  { no:  181, en: "blow", ja: "吹く／〜を吹き飛ばす", kana: "ふきとばす", ex: "The wind is blowing the leaves off the tree.", exja: "風が木から葉を【吹き飛ばして】いる。" },
  { no:  182, en: "typhoon", ja: "台風", kana: "たいふう", ex: "A strong typhoon is moving toward the island.", exja: "強い【台風】が島に向かって進んでいる。" },
  { no:  183, en: "hit", ja: "〜を襲う／〜を打つ", kana: "おそう", ex: "A huge wave hit the small fishing boat.", exja: "巨大な波が小さな漁船を【襲った】。" },
  { no:  184, en: "flood", ja: "洪水／〜を水浸しにする", kana: "こうずい", ex: "The heavy rain caused a flood in the village.", exja: "大雨が村に【洪水】を引き起こした。" },
  { no:  185, en: "warn", ja: "〜に警告する", kana: "けいこくする", ex: "The police warned drivers about the icy road.", exja: "警察は凍った道路について運転者に【警告した】。" },
  { no:  185, en: "warning", ja: "警告／注意報", kana: "ちゅういほう", ex: "The city issued a warning about heavy snow.", exja: "市は大雪の【注意報】を出した。" },
  { no:  186, en: "landslide", ja: "土砂崩れ／地すべり", kana: "どしゃくずれ", ex: "A landslide closed the mountain road for days.", exja: "【土砂崩れ】で山道が数日間通れなくなった。" },
  { no:  187, en: "occur", ja: "起こる／生じる", kana: "おこる", ex: "The accident occurred just before midnight.", exja: "その事故は真夜中の直前に【起こった】。" },
  { no:  187, en: "occurrence", ja: "出来事／発生", kana: "はっせい", ex: "Such a strong quake is a rare occurrence here.", exja: "これほど強い揺れがここで【発生】するのは珍しい。" },
  { no:  188, en: "rescue", ja: "〜を救助する", kana: "きゅうじょする", ex: "Firefighters rescued a cat from the tall tree.", exja: "消防士が高い木から猫を【救助した】。" },
  { no:  189, en: "drown", ja: "おぼれる／おぼれ死ぬ", kana: "おぼれる", ex: "He almost drowned in the deep pool.", exja: "彼は深いプールで【おぼれ】かけた。" },
  { no:  190, en: "atmosphere", ja: "雰囲気／大気", kana: "ふんいき", ex: "This small cafe has a warm atmosphere.", exja: "この小さな喫茶店は温かい【雰囲気】がある。" },
  { no:  190, en: "mood", ja: "気分／機嫌", kana: "きぶん", ex: "Good music puts my father in a happy mood.", exja: "良い音楽は父を楽しい【気分】にする。" },

  { no:  191, en: "temperature", ja: "気温／温度／体温", kana: "きおん", ex: "The temperature dropped below zero last night.", exja: "昨夜、【気温】が0度を下回った。" },
  { no:  192, en: "humid", ja: "湿気の多い／蒸し暑い", kana: "しめっぽい", ex: "Summer in this city is hot and humid.", exja: "この街の夏は暑くて【湿っぽい】。" },
  { no:  192, en: "humidity", ja: "湿度／湿気", kana: "しつど", ex: "The high humidity made the room uncomfortable.", exja: "高い【湿度】が部屋を不快にした。" },
  { no:  193, en: "degree", ja: "度／程度／学位", kana: "ていど", ex: "The two plans are similar to some degree.", exja: "その二つの計画はある【程度】似ている。" },
  { no:  194, en: "mild", ja: "穏やかな／ひかえめな", kana: "おだやかな", ex: "The winter was unusually mild this year.", exja: "今年の冬は異常に【穏やかな】天気だった。" },
  { no:  195, en: "lightning", ja: "稲妻／雷光", kana: "いなずま", ex: "Lightning lit up the whole sky for a moment.", exja: "【稲妻】が一瞬、空全体を照らした。" },
  { no:  195, en: "thunder", ja: "雷／雷鳴", kana: "かみなり", ex: "The thunder woke the baby in the night.", exja: "夜、【雷】が赤ん坊を起こした。" },
  { no:  196, en: "fog", ja: "霧", kana: "きり", ex: "Thick fog covered the harbor this morning.", exja: "濃い【霧】が今朝、港を覆った。" },
  { no:  196, en: "foggy", ja: "霧の深い", kana: "きりがふかい", ex: "The road was foggy when we left home.", exja: "家を出たとき、道は【霧が深い】状態だった。" },
  { no:  197, en: "disaster", ja: "災害／大失敗", kana: "さいがい", ex: "The town is preparing for a natural disaster.", exja: "町は自然【災害】に備えている。" },
  { no:  197, en: "disastrous", ja: "悲惨な／破滅的な", kana: "ひさんな", ex: "The new plan had a disastrous result.", exja: "その新しい計画は【悲惨な】結果になった。" },
  { no:  198, en: "earthquake", ja: "地震", kana: "じしん", ex: "A small earthquake shook our house last week.", exja: "先週、小さな【地震】が私たちの家を揺らした。" },
  { no:  199, en: "volcano", ja: "火山", kana: "かざん", ex: "That volcano has not erupted for two hundred years.", exja: "あの【火山】は200年間噴火していない。" },
  { no:  200, en: "storm", ja: "嵐／暴風雨", kana: "あらし", ex: "The storm knocked down several old trees.", exja: "【嵐】が何本かの古い木を倒した。" },
  { no:  200, en: "stormy", ja: "荒れ模様の／嵐の", kana: "あれもよう", ex: "They canceled the ferry because of stormy seas.", exja: "海が【荒れ模様】だったのでフェリーは欠航になった。" },

  { no:  201, en: "ocean", ja: "海／海洋", kana: "かいよう", ex: "The ocean looked calm from our hotel window.", exja: "ホテルの窓から【海洋】が穏やかに広がって見えた。" },
  { no:  202, en: "continent", ja: "大陸", kana: "たいりく", ex: "Africa is a continent with more than fifty countries.", exja: "アフリカは五十を超える国がある【大陸】だ。" },
  { no:  202, en: "land", ja: "陸地／土地", kana: "りくち", ex: "After three weeks at sea, the sailors finally saw land.", exja: "三週間の航海の後、船員たちはついに【陸地】を見つけた。" },
  { no:  203, en: "island", ja: "島／小島", kana: "こじま", ex: "We took a small boat to the island every summer.", exja: "私たちは毎年夏に小さな船でその【小島】へ渡った。" },
  { no:  204, en: "desert", ja: "砂漠／〜を見捨てる", kana: "さばく", ex: "Only a few tough plants grow in this dry desert.", exja: "この乾いた【砂漠】には丈夫な植物がわずかに育つだけだ。" },
  { no:  204, en: "dessert", ja: "食後の甘い物／デザート", kana: "あまいもの", ex: "My sister ordered ice cream for dessert.", exja: "妹は【甘いもの】としてアイスクリームを注文した。" },
  { no:  205, en: "valley", ja: "谷／渓谷", kana: "けいこく", ex: "A clear river runs through the quiet valley.", exja: "澄んだ川が静かな【渓谷】を流れている。" },
  { no:  206, en: "tropical", ja: "熱帯の", kana: "ねったいの", ex: "We saw many tropical birds during the boat trip.", exja: "船の旅の間に私たちは【熱帯の】鳥をたくさん見た。" },
  { no:  207, en: "climate", ja: "気候", kana: "きこう", ex: "The climate of this island is mild all year.", exja: "この島の【気候】は一年中穏やかだ。" },
  { no:  208, en: "human", ja: "人間／人間の", kana: "にんげん", ex: "No other animal builds cities the way a human does.", exja: "【人間】のように都市を築く動物は他にいない。" },
  { no:  209, en: "evolution", ja: "進化", kana: "しんか", ex: "This museum explains the evolution of birds.", exja: "この博物館は鳥の【進化】を説明している。" },
  { no:  209, en: "evolutionary", ja: "進化上の／進化に関する", kana: "しんかじょうの", ex: "Wings gave birds a great evolutionary advantage.", exja: "翼は鳥に大きな【進化上の】利点を与えた。" },
  { no:  209, en: "evolve", ja: "進化する／発展する", kana: "はってんする", ex: "Languages evolve slowly over hundreds of years.", exja: "言語は何百年もかけてゆっくりと【発展する】。" },
  { no:  210, en: "survival", ja: "生存／生き残ること", kana: "せいぞん", ex: "Clean water is necessary for survival in the mountains.", exja: "山では【生存】にきれいな水が欠かせない。" },
  { no:  210, en: "survive", ja: "生き延びる", kana: "いきのびる", ex: "Only two old trees survived the terrible fire.", exja: "ひどい火事を【生き延びた】のは古い木が二本だけだった。" },

  { no:  211, en: "revival", ja: "復活／再興", kana: "ふっかつ", ex: "The town festival had a surprising revival last spring.", exja: "その町の祭りは昨春に驚くような【復活】を遂げた。" },
  { no:  211, en: "revive", ja: "生き返る／〜を復活させる", kana: "いきかえる", ex: "A cup of hot tea revived me after the cold walk.", exja: "寒い中を歩いた後、熱いお茶で【生き返った】。" },
  { no:  212, en: "damage", ja: "損害／〜に損害を与える", kana: "そんがい", ex: "The storm did serious damage to the school roof.", exja: "嵐は学校の屋根に深刻な【損害】を与えた。" },
  { no:  213, en: "environment", ja: "環境", kana: "かんきょう", ex: "We must protect the environment for our children.", exja: "私たちは子どもたちのために【環境】を守らなければならない。" },
  { no:  213, en: "environmental", ja: "環境の", kana: "かんきょうの", ex: "She joined an environmental club at her new school.", exja: "彼女は新しい学校で【環境の】問題を扱うクラブに入った。" },
  { no:  213, en: "surroundings", ja: "周囲の様子／環境", kana: "まわり", ex: "The lost cat studied its new surroundings carefully.", exja: "迷い猫は新しい【周り】の様子を注意深く見ていた。" },
  { no:  214, en: "spoil", ja: "〜を台なしにする／甘やかす", kana: "だいなしにする", ex: "Heavy rain spoiled our picnic on Sunday.", exja: "大雨が日曜のピクニックを【台なしにした】。" },
  { no:  214, en: "spoiled", ja: "甘やかされた／だめになった", kana: "あまやかされた", ex: "The spoiled boy never helps with the dishes.", exja: "その【甘やかされた】少年は皿洗いを決して手伝わない。" },
  { no:  215, en: "view", ja: "眺め／見方", kana: "ながめ", ex: "The view from the top of the hill was wonderful.", exja: "丘の上からの【眺め】はすばらしかった。" },
  { no:  216, en: "save", ja: "〜を救う／蓄える", kana: "すくう", ex: "He saved a little girl from the cold river.", exja: "彼は冷たい川から幼い少女を【救った】。" },
  { no:  217, en: "energetic", ja: "活動的な／元気いっぱいの", kana: "かつどうてきな", ex: "Our new coach is young and energetic.", exja: "新しいコーチは若くて【活動的な】人だ。" },
  { no:  217, en: "energy", ja: "力／活力", kana: "かつりょく", ex: "Climbing the stairs uses more energy than you think.", exja: "階段を上るのは思っている以上に【活力】を使う。" },
  { no:  218, en: "poison", ja: "毒／毒物", kana: "どくぶつ", ex: "Some pretty mushrooms contain a strong poison.", exja: "きれいなキノコの中には強い【毒物】を含むものがある。" },
  { no:  218, en: "poisonous", ja: "有毒な", kana: "ゆうどくな", ex: "Never touch that poisonous snake in the grass.", exja: "草むらのあの【有毒な】ヘビには決して触るな。" },
  { no:  219, en: "substance", ja: "物質", kana: "ぶっしつ", ex: "The scientist found a strange substance in the water.", exja: "科学者は水の中に奇妙な【物質】を見つけた。" },
  { no:  220, en: "chemical", ja: "化学薬品／化学の", kana: "かがくやくひん", ex: "Some farmers use fewer chemicals on their vegetables.", exja: "野菜に使う【化学薬品】を減らしている農家もいる。" },

  { no:  221, en: "pollutant", ja: "汚染物質", kana: "おせんぶっしつ", ex: "Old buses send many pollutants into the city air.", exja: "古いバスは多くの【汚染物質】を街の空気に出す。" },
  { no:  221, en: "pollute", ja: "〜を汚染する／汚す", kana: "よごす", ex: "That factory polluted the river for thirty years.", exja: "あの工場は三十年間その川を【汚した】。" },
  { no:  221, en: "pollution", ja: "汚染／公害", kana: "こうがい", ex: "Air pollution is a serious problem in big cities.", exja: "大気の【公害】は大都市の深刻な問題だ。" },
  { no:  222, en: "garbage", ja: "生ごみ／くず", kana: "なまごみ", ex: "Please take the garbage out before dinner.", exja: "夕食の前に【生ごみ】を出しておいて。" },
  { no:  222, en: "rubbish", ja: "ごみ／がらくた", kana: "がらくた", ex: "He threw the rubbish into a big paper box.", exja: "彼は【がらくた】を大きな紙箱に投げ入れた。" },
  { no:  223, en: "litter", ja: "散らかったごみ／〜を散らかす", kana: "ちらかす", ex: "Visitors must not litter in this quiet park.", exja: "来園者はこの静かな公園でごみを【散らかして】はいけない。" },
  { no:  223, en: "trash", ja: "くず／ごみ", kana: "ごみくず", ex: "The trash can beside the door is already full.", exja: "ドアの横の箱は【ごみくず】でもういっぱいだ。" },
  { no:  224, en: "supply", ja: "供給／〜を供給する", kana: "きょうきゅう", ex: "The village has a good supply of clean water.", exja: "その村にはきれいな水の【供給】が十分にある。" },
  { no:  225, en: "electric", ja: "電気の", kana: "でんきの", ex: "My father finally bought an electric bicycle.", exja: "父はついに【電気の】自転車を買った。" },
  { no:  225, en: "electricity", ja: "電気", kana: "でんき", ex: "The storm cut off our electricity for six hours.", exja: "嵐で六時間【電気】が止まった。" },
  { no:  226, en: "reduce", ja: "〜を減らす", kana: "へらす", ex: "We should reduce the plastic we use every day.", exja: "私たちは毎日使うプラスチックを【減らす】べきだ。" },
  { no:  226, en: "reduction", ja: "削減／減少", kana: "さくげん", ex: "The company announced a reduction in ticket prices.", exja: "その会社はチケット価格の【削減】を発表した。" },
  { no:  227, en: "waist", ja: "腰／腰回り", kana: "こしまわり", ex: "He tied a thick rope around his waist.", exja: "彼は太いロープを【腰回り】に巻きつけた。" },
  { no:  227, en: "waste", ja: "〜を無駄にする／廃棄物", kana: "むだにする", ex: "Don't waste time on your phone before the exam.", exja: "試験の前にスマホで時間を【無駄にする】な。" },
  { no:  228, en: "burn", ja: "燃える／〜を燃やす", kana: "もえる", ex: "The dry leaves burned very quickly.", exja: "乾いた葉はあっという間に【燃えた】。" },
  { no:  229, en: "fossil", ja: "化石", kana: "かせき", ex: "They found a small fish fossil inside the rock.", exja: "彼らは岩の中に小さな魚の【化石】を見つけた。" },
  { no:  230, en: "fuel", ja: "燃料", kana: "ねんりょう", ex: "The plane needs extra fuel for such a long flight.", exja: "その飛行機は長い飛行のために余分な【燃料】が必要だ。" },

  { no:  231, en: "lunar", ja: "月の", kana: "つきの", ex: "A lunar month is about twenty-nine days long.", exja: "【月の】暦の一か月はおよそ二十九日の長さだ。" },
  { no:  231, en: "solar", ja: "太陽の", kana: "たいようの", ex: "Our school put solar panels on the gym roof.", exja: "私たちの学校は体育館の屋根に【太陽の】光を集めるパネルを設置した。" },
  { no:  231, en: "sun", ja: "太陽", kana: "たいよう", ex: "The sun rose slowly behind the eastern mountains.", exja: "【太陽】は東の山の向こうからゆっくり昇った。" },
  { no:  232, en: "generate", ja: "〜を生み出す", kana: "うみだす", ex: "Wind can generate electricity without any smoke.", exja: "風は煙を出さずに電気を【生み出す】ことができる。" },
  { no:  232, en: "generation", ja: "世代", kana: "せだい", ex: "My grandmother's generation lived through hard times.", exja: "祖母の【世代】は苦しい時代を生き抜いた。" },
  { no:  232, en: "generator", ja: "発電機", kana: "はつでんき", ex: "The hospital used a generator during the power cut.", exja: "病院は停電の間、【発電機】を使った。" },
  { no:  233, en: "greenhouse", ja: "温室", kana: "おんしつ", ex: "Tomatoes grow well inside this warm greenhouse.", exja: "トマトはこの暖かい【温室】の中でよく育つ。" },
  { no:  234, en: "resource", ja: "資源", kana: "しげん", ex: "Japan has few natural resources of its own.", exja: "日本には自国の天然【資源】が乏しい。" },
  { no:  234, en: "source", ja: "源／出所", kana: "みなもと", ex: "The source of this river is high in the mountains.", exja: "この川の【源】は山の高いところにある。" },
  { no:  235, en: "material", ja: "材料／素材", kana: "ざいりょう", ex: "We need soft material to make these dolls.", exja: "この人形を作るには柔らかい【材料】が必要だ。" },
  { no:  238, en: "soon", ja: "まもなく／すぐに", kana: "まもなく", ex: "The last train will leave soon, so hurry up.", exja: "終電は【まもなく】出るから急いで。" },
  { no:  242, en: "nowadays", ja: "近頃／最近では", kana: "ちかごろ", ex: "Nowadays many students study with tablets.", exja: "【近頃】は多くの生徒がタブレットで勉強する。" },
  { no:  246, en: "past", ja: "過去／昔", kana: "むかし", ex: "Forget the past and think about tomorrow.", exja: "【昔】のことは忘れて明日のことを考えよう。" },
  { no:  247, en: "future", ja: "未来／将来", kana: "みらい", ex: "She hopes to work as a nurse in the future.", exja: "彼女は【未来】に看護師として働くことを望んでいる。" },
  { no:  250, en: "middle", ja: "真ん中／中央", kana: "まんなか", ex: "A huge tree stands in the middle of the field.", exja: "巨大な木が野原の【真ん中】に立っている。" },
  { no:  252, en: "beside", ja: "〜のそばに", kana: "そばに", ex: "A little brown dog sat beside my chair.", exja: "小さな茶色の犬が私の椅子の【そばに】座った。" },
  { no:  253, en: "distance", ja: "距離", kana: "きょり", ex: "The distance between the two towns is ten kilometers.", exja: "その二つの町の【距離】は十キロだ。" },
  { no:  253, en: "distant", ja: "遠い／離れた", kana: "とおい", ex: "We heard a distant bell through the thick fog.", exja: "濃い霧の中から【遠い】鐘の音が聞こえた。" },
  { no:  255, en: "favor", ja: "好意／親切な行い", kana: "こうい", ex: "Can I ask you a small favor this afternoon?", exja: "今日の午後、一つ【好意】をお願いしてもいいですか。" },
  { no:  255, en: "favorable", ja: "好意的な／有利な", kana: "ゆうりな", ex: "The wind was favorable for the little sailing boat.", exja: "風は小さなヨットにとって【有利な】ものだった。" },
  { no:  260, en: "review", ja: "〜を復習する／批評", kana: "ふくしゅうする", ex: "I review my notes every night before bed.", exja: "私は毎晩寝る前にノートを【復習する】。" },
  { no:  260, en: "revise", ja: "〜を修正する／見直す", kana: "しゅうせいする", ex: "She revised her essay after hearing her teacher's advice.", exja: "彼女は先生の助言を聞いて作文を【修正した】。" },
  { no:  268, en: "grant", ja: "〜を与える／認める", kana: "あたえる", ex: "The king granted land to the young soldier.", exja: "王は若い兵士に土地を【与えた】。" },
  { no:  269, en: "pride", ja: "誇り／自尊心", kana: "ほこり", ex: "He spoke about his hometown with real pride.", exja: "彼は心からの【誇り】を持って故郷について語った。" },
  { no:  269, en: "proud", ja: "誇りに思って", kana: "ほこらしい", ex: "My parents were proud of my speech.", exja: "両親は私のスピーチを【誇らしい】と感じてくれた。" },
  { no:  270, en: "absence", ja: "欠席／不在", kana: "けっせき", ex: "Her absence from practice surprised the whole team.", exja: "彼女の練習の【欠席】はチーム全員を驚かせた。" },
  { no:  270, en: "absent", ja: "欠席の／不在の", kana: "ふざいの", ex: "Three students were absent because of the flu.", exja: "インフルエンザで三人の生徒が【不在の】状態だった。" },
  { no:  273, en: "famous", ja: "有名な", kana: "ゆうめいな", ex: "This small town is famous for its old castle.", exja: "この小さな町は古い城で【有名な】場所だ。" },
  { no:  276, en: "exchange", ja: "〜を交換する／交換", kana: "こうかんする", ex: "We exchanged phone numbers at the school festival.", exja: "私たちは学園祭で電話番号を【交換した】。" },
  { no:  278, en: "invitation", ja: "招待／招待状", kana: "しょうたい", ex: "I received an invitation to my cousin's wedding.", exja: "いとこの結婚式の【招待】状が届いた。" },
  { no:  278, en: "invite", ja: "〜を招待する", kana: "まねく", ex: "They invited us to dinner next Saturday.", exja: "彼らは次の土曜の夕食に私たちを【招いて】くれた。" },
  { no:  279, en: "add", ja: "〜を加える", kana: "くわえる", ex: "Add a little salt to the soup at the end.", exja: "最後にスープに少し塩を【加え】なさい。" },
  { no:  279, en: "addition", ja: "追加／足し算", kana: "ついか", ex: "The addition of one room made the house much better.", exja: "一部屋の【追加】で家はずっと良くなった。" },
  { no:  279, en: "additional", ja: "追加の／さらなる", kana: "さらなる", ex: "We need additional chairs for tonight's guests.", exja: "今夜の客のために【さらなる】椅子が必要だ。" },
  { no:  280, en: "prefer", ja: "〜をより好む", kana: "このむ", ex: "I prefer green tea to coffee in the morning.", exja: "私は朝はコーヒーより緑茶を【好む】。" },
  { no:  287, en: "postpone", ja: "〜を延期する", kana: "えんきする", ex: "They postponed the match because of heavy rain.", exja: "大雨のため彼らは試合を【延期した】。" },
  { no:  288, en: "extinguish", ja: "〜を消す／消火する", kana: "しょうかする", ex: "Firefighters extinguished the fire in less than an hour.", exja: "消防士たちは一時間もかからずに【消火した】。" },
  { no:  292, en: "participant", ja: "参加者", kana: "さんかしゃ", ex: "Every participant received a small towel as a gift.", exja: "【参加者】は全員おみやげに小さなタオルをもらった。" },
  { no:  292, en: "participate", ja: "参加する", kana: "さんかする", ex: "Many students participated in the river cleaning event.", exja: "多くの生徒が川の清掃行事に【参加した】。" },
  { no:  292, en: "participation", ja: "参加", kana: "さんか", ex: "Your participation in tomorrow's meeting is welcome.", exja: "明日の会議へのあなたの【参加】を歓迎します。" },
  { no:  293, en: "perform", ja: "〜を行う／演じる", kana: "おこなう", ex: "The band performed three new songs that night.", exja: "そのバンドはその夜、新曲三曲の演奏を【行った】。" },
  { no:  293, en: "performance", ja: "演技／出来栄え", kana: "えんぎ", ex: "Her performance on the stage moved the whole audience.", exja: "舞台での彼女の【演技】は観客全員を感動させた。" },
  { no:  294, en: "task", ja: "仕事／課題", kana: "しごと", ex: "My first task was to clean the windows.", exja: "私の最初の【仕事】は窓を掃除することだった。" },
  { no:  295, en: "negative", ja: "否定的な／悪い", kana: "ひていてきな", ex: "He gave a negative answer to my simple question.", exja: "彼は私の簡単な質問に【否定的な】答えをした。" },
  { no:  295, en: "positive", ja: "肯定的な／前向きな", kana: "まえむきな", ex: "Try to keep a positive mind before the test.", exja: "試験の前は【前向きな】気持ちを保つようにしよう。" },
  { no:  296, en: "attitude", ja: "態度／考え方", kana: "たいど", ex: "His attitude toward homework changed this year.", exja: "宿題に対する彼の【態度】は今年変わった。" },
  { no:  296, en: "posture", ja: "姿勢", kana: "しせい", ex: "Good posture helps you study for a long time.", exja: "良い【姿勢】は長時間の勉強を助ける。" },
  { no:  298, en: "image", ja: "印象／画像", kana: "いんしょう", ex: "The image on the old screen was too dark.", exja: "古い画面が与える【印象】は暗すぎた。" },
  { no:  298, en: "imagination", ja: "想像力", kana: "そうぞうりょく", ex: "Young children often have a rich imagination.", exja: "幼い子どもはしばしば豊かな【想像力】を持つ。" },
  { no:  298, en: "imagine", ja: "〜を想像する", kana: "そうぞうする", ex: "Imagine a city without any cars at all.", exja: "車が一台もない街を【想像して】ごらん。" },
  { no:  299, en: "judge", ja: "〜を判断する／裁判官", kana: "はんだんする", ex: "Don't judge a person by their clothes.", exja: "服装で人を【判断して】はいけない。" },
  { no:  299, en: "judgment", ja: "判断／判決", kana: "はんだん", ex: "I trust your judgment in this difficult case.", exja: "この難しい件ではあなたの【判断】を信じます。" },
  { no:  300, en: "appear", ja: "現れる／〜のように見える", kana: "あらわれる", ex: "A bright rainbow appeared after the evening rain.", exja: "夕方の雨の後に鮮やかな虹が【現れた】。" },
  { no:  300, en: "appearance", ja: "外見／出現", kana: "がいけん", ex: "His appearance changed a lot during the long trip.", exja: "長い旅の間に彼の【外見】はずいぶん変わった。" },
];



// ---------------------------------------------------------------
// 収録範囲（メニューの初期表示に使う）
function getJukenMeta() {
  const nos = JUKEN_WORDS.map(w => w.no);
  return {
    total: JUKEN_WORDS.length,
    minNo: Math.min.apply(null, nos),
    maxNo: Math.max.apply(null, nos)
  };
}

// ---------------------------------------------------------------
// 出題データ取得
//   opts.from / opts.to : 見出し語番号の範囲（省略すると全範囲）
//   opts.limit          : 1回の出題数
//   opts.shuffle        : true ならシャッフル、false なら番号の若い順
function getJukenWords(opts) {
  opts = opts || {};
  const from  = Number(opts.from)  || 0;
  const to    = Number(opts.to)    || 0;
  const limit = Number(opts.limit) || 20;

  let words = JUKEN_WORDS.filter(w =>
    (!from || w.no >= from) && (!to || w.no <= to)
  );

  const matched = words.length;

  if (opts.shuffle) {
    for (let i = words.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [words[i], words[j]] = [words[j], words[i]];
    }
  } else {
    words.sort((a, b) => a.no - b.no);
  }

  return { words: words.slice(0, limit), matched: matched };
}
